/* Copyright 2018-2024, Stephen Fryatt (info@stevefryatt.org.uk)
 *
 * This file is part of XmlMan:
 *
 *   http://www.stevefryatt.org.uk/risc-os
 *
 * Licensed under the EUPL, Version 1.2 only (the "Licence");
 * You may not use this work except in compliance with the
 * Licence.
 *
 * You may obtain a copy of the Licence at:
 *
 *   http://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in
 * writing, software distributed under the Licence is
 * distributed on an "AS IS" basis, WITHOUT WARRANTIES
 * OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the Licence for the specific language governing
 * permissions and limitations under the Licence.
 */

/**
 * \file manual_entity.h
 *
 * XML Manual Entity Decoding Interface.
 */

#ifndef XMLMAN_MANUAL_ENTITY_H
#define XMLMAN_MANUAL_ENTITY_H

/**
 * No Unicode codepoint is available.
 */

#define MANUAL_ENTITY_NO_CODEPOINT (-1)

/**
 * A list of entities known to the parser.
 *
 * It *must* correspond to the order that the entity values are
 * defined in manual_entity.c, so that the array indices match the
 * values of their enum entries.
 *
 * The values in that table are ordered by ascending unicode point,
 * with non-unicode entities at the start using -1 and NONE at the
 * end as an end stop. The order of the entity texts are not important.
 */

enum manual_entity_type {
	/* Non-Standard Special Cases */

	MANUAL_ENTITY_SMILEYFACE,
	MANUAL_ENTITY_SADFACE,
	MANUAL_ENTITY_MSEP,

	/* Basic Latin */

	MANUAL_ENTITY_TAB,			// 0x9
	MANUAL_ENTITY_NEWLINE,			// 0xa
	MANUAL_ENTITY_EXCL,			// 0x21
	MANUAL_ENTITY_QUOT,			// 0x22
	MANUAL_ENTITY_NUM,			// 0x23
	MANUAL_ENTITY_DOLLAR,			// 0x24
	MANUAL_ENTITY_PERCNT,			// 0x25
	MANUAL_ENTITY_AMP,			// 0x26
	MANUAL_ENTITY_APOS,			// 0x27
	MANUAL_ENTITY_LPAR,			// 0x28
	MANUAL_ENTITY_RPAR,			// 0x29
	MANUAL_ENTITY_AST,			// 0x2a
	MANUAL_ENTITY_PLUS,			// 0x2b
	MANUAL_ENTITY_COMMA,			// 0x2c
	MANUAL_ENTITY_PERIOD,			// 0x2e
	MANUAL_ENTITY_SOL,			// 0x2f
	MANUAL_ENTITY_COLON,			// 0x3a
	MANUAL_ENTITY_SEMI,			// 0x3b
	MANUAL_ENTITY_LT,			// 0x3c
	MANUAL_ENTITY_EQUALS,			// 0x3d
	MANUAL_ENTITY_GT,			// 0x3e
	MANUAL_ENTITY_QUEST,			// 0x3f
	MANUAL_ENTITY_COMMAT,			// 0x40
	MANUAL_ENTITY_LBRACK,			// 0x5b
	MANUAL_ENTITY_BSOL,			// 0x5c
	MANUAL_ENTITY_RBRACK,			// 0x5d
	MANUAL_ENTITY_HAT,			// 0x5e
	MANUAL_ENTITY_UNDERBAR,			// 0x5f
	MANUAL_ENTITY_DIACRITICALGRAVE,		// 0x60
	MANUAL_ENTITY_LBRACE,			// 0x7b
	MANUAL_ENTITY_VERTICALLINE,		// 0x7c
	MANUAL_ENTITY_RBRACE,			// 0x7d

	/* Latin-1 Supplement */

	MANUAL_ENTITY_NBSP,			// 0xa0
	MANUAL_ENTITY_IEXCL,			// 0xa1
	MANUAL_ENTITY_CENT,			// 0xa2
	MANUAL_ENTITY_POUND,			// 0xa3
	MANUAL_ENTITY_CURREN,			// 0xa4
	MANUAL_ENTITY_YEN,			// 0xa5
	MANUAL_ENTITY_BRVBAR,			// 0xa6
	MANUAL_ENTITY_SECT,			// 0xa7
	MANUAL_ENTITY_UML,			// 0xa8
	MANUAL_ENTITY_COPY,			// 0xa9
	MANUAL_ENTITY_ORDF_L,			// 0xaa
	MANUAL_ENTITY_LAQUO,			// 0xab
	MANUAL_ENTITY_NOT,			// 0xac
	MANUAL_ENTITY_SHY,			// 0xad
	MANUAL_ENTITY_REG,			// 0xae
	MANUAL_ENTITY_MACR,			// 0xaf
	MANUAL_ENTITY_DEG,			// 0xb0
	MANUAL_ENTITY_PLUSMN,			// 0xb1
	MANUAL_ENTITY_SUP2,			// 0xb2
	MANUAL_ENTITY_SUP3,			// 0xb3
	MANUAL_ENTITY_ACUTE,			// 0xb4
	MANUAL_ENTITY_MICRO_L,			// 0xb5
	MANUAL_ENTITY_PARA,			// 0xb6
	MANUAL_ENTITY_MIDDOT,			// 0xb7
	MANUAL_ENTITY_CEDIL,			// 0xb8
	MANUAL_ENTITY_SUP1,			// 0xb9
	MANUAL_ENTITY_ORDM_L,			// 0xba
	MANUAL_ENTITY_RAQUO,			// 0xbb
	MANUAL_ENTITY_FRAC14,			// 0xbc
	MANUAL_ENTITY_FRAC12,			// 0xbd
	MANUAL_ENTITY_FRAC34,			// 0xbe
	MANUAL_ENTITY_IQUEST,			// 0xbf
	MANUAL_ENTITY_AGRAVE_U,			// 0xc0
	MANUAL_ENTITY_AACUTE_U,			// 0xc1
	MANUAL_ENTITY_ACIRC_U,			// 0xc2
	MANUAL_ENTITY_ATILDE_U,			// 0xc3
	MANUAL_ENTITY_AUML_U,			// 0xc4
	MANUAL_ENTITY_ARING_U,			// 0xc5
	MANUAL_ENTITY_AELIG_U,			// 0xc6
	MANUAL_ENTITY_CCEDIL_U,			// 0xc7
	MANUAL_ENTITY_EGRAVE_U,			// 0xc8
	MANUAL_ENTITY_EACUTE_U,			// 0xc9
	MANUAL_ENTITY_ECIRC_U,			// 0xca
	MANUAL_ENTITY_EUML_U,			// 0xcb
	MANUAL_ENTITY_IGRAVE_U,			// 0xcc
	MANUAL_ENTITY_IACUTE_U,			// 0xcd
	MANUAL_ENTITY_ICIRC_U,			// 0xce
	MANUAL_ENTITY_IUML_U,			// 0xcf
	MANUAL_ENTITY_ETH_U,			// 0xd0
	MANUAL_ENTITY_NTILDE_U,			// 0xd1
	MANUAL_ENTITY_OGRAVE_U,			// 0xd2
	MANUAL_ENTITY_OACUTE_U,			// 0xd3
	MANUAL_ENTITY_OCIRC_U,			// 0xd4
	MANUAL_ENTITY_OTILDE_U,			// 0xd5
	MANUAL_ENTITY_OUML_U,			// 0xd6
	MANUAL_ENTITY_TIMES,			// 0xd7
	MANUAL_ENTITY_OSLASH_U,			// 0xd8
	MANUAL_ENTITY_UGRAVE_U,			// 0xd9
	MANUAL_ENTITY_UACUTE_U,			// 0xda
	MANUAL_ENTITY_UCIRC_U,			// 0xdb
	MANUAL_ENTITY_UUML_U,			// 0xdc
	MANUAL_ENTITY_YACUTE_U,			// 0xdd
	MANUAL_ENTITY_THORN_U,			// 0xde
	MANUAL_ENTITY_SZLIG_L,			// 0xdf
	MANUAL_ENTITY_AGRAVE_L,			// 0xe0
	MANUAL_ENTITY_AACUTE_L,			// 0xe1
	MANUAL_ENTITY_ACIRC_L,			// 0xe2
	MANUAL_ENTITY_ATILDE_L,			// 0xe3
	MANUAL_ENTITY_AUML_L,			// 0xe4
	MANUAL_ENTITY_ARING_L,			// 0xe5
	MANUAL_ENTITY_AELIG_L,			// 0xe6
	MANUAL_ENTITY_CCEDIL_L,			// 0xe7
	MANUAL_ENTITY_EGRAVE_L,			// 0xe8
	MANUAL_ENTITY_EACUTE_L,			// 0xe9
	MANUAL_ENTITY_ECIRC_L,			// 0xea
	MANUAL_ENTITY_EUML_L,			// 0xeb
	MANUAL_ENTITY_IGRAVE_L,			// 0xec
	MANUAL_ENTITY_IACUTE_L,			// 0xed
	MANUAL_ENTITY_ICIRC_L,			// 0xee
	MANUAL_ENTITY_IUML_L,			// 0xef
	MANUAL_ENTITY_ETH_L,			// 0xf0
	MANUAL_ENTITY_NTILDE_L,			// 0xf1
	MANUAL_ENTITY_OGRAVE_L,			// 0xf2
	MANUAL_ENTITY_OACUTE_L,			// 0xf3
	MANUAL_ENTITY_OCIRC_L,			// 0xf4
	MANUAL_ENTITY_OTILDE_L,			// 0xf5
	MANUAL_ENTITY_OUML_L,			// 0xf6
	MANUAL_ENTITY_DIVIDE,			// 0xf7
	MANUAL_ENTITY_OSLASH_L,			// 0xf8
	MANUAL_ENTITY_UGRAVE_L,			// 0xf9
	MANUAL_ENTITY_UACUTE_L,			// 0xfa
	MANUAL_ENTITY_UCIRC_L,			// 0xfb
	MANUAL_ENTITY_UUML_L,			// 0xfc
	MANUAL_ENTITY_YACUTE_L,			// 0xfd
	MANUAL_ENTITY_THORN_L,			// 0xfe
	MANUAL_ENTITY_YUML_L,			// 0xff

	/* Latin Extended A */

	MANUAL_ENTITY_AMACR_U,			// 0x100
	MANUAL_ENTITY_AMACR_L,			// 0x101
	MANUAL_ENTITY_ABREVE_U,			// 0x102
	MANUAL_ENTITY_ABREVE_L,			// 0x103
	MANUAL_ENTITY_AOGON_U,			// 0x104
	MANUAL_ENTITY_AOGON_L,			// 0x105
	MANUAL_ENTITY_CACUTE_U,			// 0x106
	MANUAL_ENTITY_CACUTE_L,			// 0x107
	MANUAL_ENTITY_CCIRC_U,			// 0x108
	MANUAL_ENTITY_CCIRC_L,			// 0x109
	MANUAL_ENTITY_CDOT_U,			// 0x10a
	MANUAL_ENTITY_CDOT_L,			// 0x10b
	MANUAL_ENTITY_CCARON_U,			// 0x10c
	MANUAL_ENTITY_CCARON_L,			// 0x10d
	MANUAL_ENTITY_DCARON_U,			// 0x10e
	MANUAL_ENTITY_DCARON_L,			// 0x10f
	MANUAL_ENTITY_DSTROK_U,			// 0x110
	MANUAL_ENTITY_DSTROK_L,			// 0x111
	MANUAL_ENTITY_EMACR_U,			// 0x112
	MANUAL_ENTITY_EMACR_L,			// 0x113
	MANUAL_ENTITY_EDOT_U,			// 0x116
	MANUAL_ENTITY_EDOT_L,			// 0x117
	MANUAL_ENTITY_EOGON_U,			// 0x118
	MANUAL_ENTITY_EOGON_L,			// 0x119
	MANUAL_ENTITY_ECARON_U,			// 0x11a
	MANUAL_ENTITY_ECARON_L,			// 0x11b
	MANUAL_ENTITY_GCIRC_U,			// 0x11c
	MANUAL_ENTITY_GCIRC_L,			// 0x11d
	MANUAL_ENTITY_GBREVE_U,			// 0x11e
	MANUAL_ENTITY_GBREVE_L,			// 0x11f
	MANUAL_ENTITY_GDOT_U,			// 0x120
	MANUAL_ENTITY_GDOT_L,			// 0x121
	MANUAL_ENTITY_GCEDIL_U,			// 0x122
	MANUAL_ENTITY_HCIRC_U,			// 0x124
	MANUAL_ENTITY_HCIRC_L,			// 0x125
	MANUAL_ENTITY_HSTROK_U,			// 0x126
	MANUAL_ENTITY_HSTROK_L,			// 0x127
	MANUAL_ENTITY_ITILDE_U,			// 0x128
	MANUAL_ENTITY_ITILDE_L,			// 0x129
	MANUAL_ENTITY_IMACR_U,			// 0x12a
	MANUAL_ENTITY_IMACR_L,			// 0x12b
	MANUAL_ENTITY_IOGON_U,			// 0x12e
	MANUAL_ENTITY_IOGON_L,			// 0x12f
	MANUAL_ENTITY_IDOT_U,			// 0x130
	MANUAL_ENTITY_IMATH_L,			// 0x131
	MANUAL_ENTITY_IJLIG_U,			// 0x132
	MANUAL_ENTITY_IJLIG_L,			// 0x133
	MANUAL_ENTITY_JCIRC_U,			// 0x134
	MANUAL_ENTITY_JCIRC_L,			// 0x135
	MANUAL_ENTITY_KCEDIL_U,			// 0x136
	MANUAL_ENTITY_KCEDIL_L,			// 0x137
	MANUAL_ENTITY_KGREEN_L,			// 0x138
	MANUAL_ENTITY_LACUTE_U,			// 0x139
	MANUAL_ENTITY_LACUTE_L,			// 0x13a
	MANUAL_ENTITY_LCEDIL_U,			// 0x13b
	MANUAL_ENTITY_LCEDIL_L,			// 0x13c
	MANUAL_ENTITY_LCARON_U,			// 0x13d
	MANUAL_ENTITY_LCARON_L,			// 0x13e
	MANUAL_ENTITY_LMIDOT_U,			// 0x13f
	MANUAL_ENTITY_LMIDOT_L,			// 0x140
	MANUAL_ENTITY_LSTROK_U,			// 0x141
	MANUAL_ENTITY_LSTROK_L,			// 0x142
	MANUAL_ENTITY_NACUTE_U,			// 0x143
	MANUAL_ENTITY_NACUTE_L,			// 0x144
	MANUAL_ENTITY_NCEDIL_U,			// 0x145
	MANUAL_ENTITY_NCEDIL_L,			// 0x146
	MANUAL_ENTITY_NCARON_U,			// 0x147
	MANUAL_ENTITY_NCARON_L,			// 0x148
	MANUAL_ENTITY_NAPOS_L,			// 0x149
	MANUAL_ENTITY_ENG_U,			// 0x14a
	MANUAL_ENTITY_ENG_L,			// 0x14b
	MANUAL_ENTITY_OMACR_U,			// 0x14c
	MANUAL_ENTITY_OMACR_L,			// 0x14d
	MANUAL_ENTITY_ODBLAC_U,			// 0x150
	MANUAL_ENTITY_ODBLAC_L,			// 0x151
	MANUAL_ENTITY_OELIG_U,			// 0x152
	MANUAL_ENTITY_OELIG_L,			// 0x153
	MANUAL_ENTITY_RACUTE_U,			// 0x154
	MANUAL_ENTITY_RACUTE_L,			// 0x155
	MANUAL_ENTITY_RCEDIL_U,			// 0x156
	MANUAL_ENTITY_RCEDIL_L,			// 0x157
	MANUAL_ENTITY_RCARON_U,			// 0x158
	MANUAL_ENTITY_RCARON_L,			// 0x159
	MANUAL_ENTITY_SACUTE_U,			// 0x15a
	MANUAL_ENTITY_SACUTE_L,			// 0x15b
	MANUAL_ENTITY_SCIRC_U,			// 0x15c
	MANUAL_ENTITY_SCIRC_L,			// 0x15d
	MANUAL_ENTITY_SCEDIL_U,			// 0x15e
	MANUAL_ENTITY_SCEDIL_L,			// 0x15f
	MANUAL_ENTITY_SCARON_U,			// 0x160
	MANUAL_ENTITY_SCARON_L,			// 0x161
	MANUAL_ENTITY_TCEDIL_U,			// 0x162
	MANUAL_ENTITY_TCEDIL_L,			// 0x163
	MANUAL_ENTITY_TCARON_U,			// 0x164
	MANUAL_ENTITY_TCARON_L,			// 0x165
	MANUAL_ENTITY_TSTROK_U,			// 0x166
	MANUAL_ENTITY_TSTROK_L,			// 0x167
	MANUAL_ENTITY_UTILDE_U,			// 0x168
	MANUAL_ENTITY_UTILDE_L,			// 0x169
	MANUAL_ENTITY_UMACR_U,			// 0x16a
	MANUAL_ENTITY_UMACR_L,			// 0x16b
	MANUAL_ENTITY_UBREVE_U,			// 0x16c
	MANUAL_ENTITY_UBREVE_L,			// 0x16d
	MANUAL_ENTITY_URING_U,			// 0x16e
	MANUAL_ENTITY_URING_L,			// 0x16f
	MANUAL_ENTITY_UDBLAC_U,			// 0x170
	MANUAL_ENTITY_UDBLAC_L,			// 0x171
	MANUAL_ENTITY_UOGON_U,			// 0x172
	MANUAL_ENTITY_UOGON_L,			// 0x173
	MANUAL_ENTITY_WCIRC_U,			// 0x174
	MANUAL_ENTITY_WCIRC_L,			// 0x175
	MANUAL_ENTITY_YCIRC_U,			// 0x176
	MANUAL_ENTITY_YCIRC_L,			// 0x177
	MANUAL_ENTITY_YUML_U,			// 0x178
	MANUAL_ENTITY_ZACUTE_U,			// 0x179
	MANUAL_ENTITY_ZACUTE_L,			// 0x17a
	MANUAL_ENTITY_ZDOT_U,			// 0x17b
	MANUAL_ENTITY_ZDOT_L,			// 0x17c
	MANUAL_ENTITY_ZCARON_U,			// 0x17d
	MANUAL_ENTITY_ZCARON_L,			// 0x17e

	/* Latin Extended B */

	MANUAL_ENTITY_FNOF_L,			// 0x192
	MANUAL_ENTITY_IMPED_U,			// 0x1b5
	MANUAL_ENTITY_GACUTE_L,			// 0x1f5
	MANUAL_ENTITY_JMATH_L,			// 0x237

	/* Spacing Modifier Letter */

	MANUAL_ENTITY_CIRC,			// 0x2c6
	MANUAL_ENTITY_HACEK,			// 0x2c7
	MANUAL_ENTITY_BREVE,			// 0x2d8
	MANUAL_ENTITY_DIACRITICALDOT,		// 0x2d9
	MANUAL_ENTITY_RING,			// 0x2da
	MANUAL_ENTITY_OGON,			// 0x2db
	MANUAL_ENTITY_TILDE,			// 0x2dc
	MANUAL_ENTITY_DIACRITICALDOUBLEACUTE,	// 0x2dd

	/* Combining Diacritical Marks */

	MANUAL_ENTITY_DOWNBREVE,		// 0x311

	/* Greek and Coptic */

	MANUAL_ENTITY_ALPHA_U,			// 0x391
	MANUAL_ENTITY_BETA_U,			// 0x392
	MANUAL_ENTITY_GAMMA_U,			// 0x393
	MANUAL_ENTITY_DELTA_U,			// 0x394
	MANUAL_ENTITY_EPSILON_U,		// 0x395
	MANUAL_ENTITY_ZETA_U,			// 0x396
	MANUAL_ENTITY_ETA_U,			// 0x397
	MANUAL_ENTITY_THETA_U,			// 0x398
	MANUAL_ENTITY_IOTA_U,			// 0x399
	MANUAL_ENTITY_KAPPA_U,			// 0x39a
	MANUAL_ENTITY_LAMBDA_U,			// 0x39b
	MANUAL_ENTITY_MU_U,			// 0x39c
	MANUAL_ENTITY_NU_U,			// 0x39d
	MANUAL_ENTITY_XI_U,			// 0x39e
	MANUAL_ENTITY_OMICRON_U,		// 0x39f
	MANUAL_ENTITY_PI_U,			// 0x3a0
	MANUAL_ENTITY_RHO_U,			// 0x3a1
	MANUAL_ENTITY_SIGMA_U,			// 0x3a3
	MANUAL_ENTITY_TAU_U,			// 0x3a4
	MANUAL_ENTITY_UPSILON_U,		// 0x3a5
	MANUAL_ENTITY_PHI_U,			// 0x3a6
	MANUAL_ENTITY_CHI_U,			// 0x3a7
	MANUAL_ENTITY_PSI_U,			// 0x3a8
	MANUAL_ENTITY_OMEGA_U,			// 0x3a9
	MANUAL_ENTITY_ALPHA_L,			// 0x3b1
	MANUAL_ENTITY_BETA_L,			// 0x3b2
	MANUAL_ENTITY_GAMMA_L,			// 0x3b3
	MANUAL_ENTITY_DELTA_L,			// 0x3b4
	MANUAL_ENTITY_EPSILON_L,		// 0x3b5
	MANUAL_ENTITY_ZETA_L,			// 0x3b6
	MANUAL_ENTITY_ETA_L,			// 0x3b7
	MANUAL_ENTITY_THETA_L,			// 0x3b8
	MANUAL_ENTITY_IOTA_L,			// 0x3b9
	MANUAL_ENTITY_KAPPA_L,			// 0x3ba
	MANUAL_ENTITY_LAMBDA_L,			// 0x3bb
	MANUAL_ENTITY_MU_L,			// 0x3bc
	MANUAL_ENTITY_NU_L,			// 0x3bd
	MANUAL_ENTITY_XI_L,			// 0x3be
	MANUAL_ENTITY_OMICRON_L,		// 0x3bf
	MANUAL_ENTITY_PI_L,			// 0x3c0
	MANUAL_ENTITY_RHO_L,			// 0x3c1
	MANUAL_ENTITY_SIGMAF_L,			// 0x3c2
	MANUAL_ENTITY_SIGMA_L,			// 0x3c3
	MANUAL_ENTITY_TAU_L,			// 0x3c4
	MANUAL_ENTITY_UPSILON_L,		// 0x3c5
	MANUAL_ENTITY_PHI_L,			// 0x3c6
	MANUAL_ENTITY_CHI_L,			// 0x3c7
	MANUAL_ENTITY_PSI_L,			// 0x3c8
	MANUAL_ENTITY_OMEGA_L,			// 0x3c9
	MANUAL_ENTITY_THETASYM_L,		// 0x3d1
	MANUAL_ENTITY_UPSIH_U,			// 0x3d2
	MANUAL_ENTITY_PHIV_L,			// 0x3d5
	MANUAL_ENTITY_PIV_L,			// 0x3d6
	MANUAL_ENTITY_GAMMAD_U,			// 0x3dc
	MANUAL_ENTITY_DIGAMMA_L,		// 0x3dd
	MANUAL_ENTITY_KAPPAV_L,			// 0x3f0
	MANUAL_ENTITY_RHOV_L,			// 0x3f1
	MANUAL_ENTITY_EPSIV_L,			// 0x3f5
	MANUAL_ENTITY_BACKEPSILON,		// 0x3f6

	/* Cyrillic */

	MANUAL_ENTITY_IOCY_U,			// 0x401
	MANUAL_ENTITY_DJCY_U,			// 0x402
	MANUAL_ENTITY_GJCY_U,			// 0x403
	MANUAL_ENTITY_JUKCY_U,			// 0x404
	MANUAL_ENTITY_DSCY_U,			// 0x405
	MANUAL_ENTITY_IUKCY_U,			// 0x406
	MANUAL_ENTITY_YICY_U,			// 0x407
	MANUAL_ENTITY_JSERCY_U,			// 0x408
	MANUAL_ENTITY_LJCY_U,			// 0x409
	MANUAL_ENTITY_NJCY_U,			// 0x40a
	MANUAL_ENTITY_TSHCY_U,			// 0x40b
	MANUAL_ENTITY_KJCY_U,			// 0x40c
	MANUAL_ENTITY_UBRCY_U,			// 0x40e
	MANUAL_ENTITY_DZCY_U,			// 0x40f
	MANUAL_ENTITY_ACY_U,			// 0x410
	MANUAL_ENTITY_BCY_U,			// 0x411
	MANUAL_ENTITY_VCY_U,			// 0x412
	MANUAL_ENTITY_GCY_U,			// 0x413
	MANUAL_ENTITY_DCY_U,			// 0x414
	MANUAL_ENTITY_IECY_U,			// 0x415
	MANUAL_ENTITY_ZHCY_U,			// 0x416
	MANUAL_ENTITY_ZCY_U,			// 0x417
	MANUAL_ENTITY_ICY_U,			// 0x418
	MANUAL_ENTITY_JCY_U,			// 0x419
	MANUAL_ENTITY_KCY_U,			// 0x41a
	MANUAL_ENTITY_LCY_U,			// 0x41b
	MANUAL_ENTITY_MCY_U,			// 0x41c
	MANUAL_ENTITY_NCY_U,			// 0x41d
	MANUAL_ENTITY_OCY_U,			// 0x41e
	MANUAL_ENTITY_PCY_U,			// 0x41f
	MANUAL_ENTITY_RCY_U,			// 0x420
	MANUAL_ENTITY_SCY_U,			// 0x421
	MANUAL_ENTITY_TCY_U,			// 0x422
	MANUAL_ENTITY_UCY_U,			// 0x423
	MANUAL_ENTITY_FCY_U,			// 0x424
	MANUAL_ENTITY_KHCY_U,			// 0x425
	MANUAL_ENTITY_TSCY_U,			// 0x426
	MANUAL_ENTITY_CHCY_U,			// 0x427
	MANUAL_ENTITY_SHCY_U,			// 0x428
	MANUAL_ENTITY_SHCHCY_U,			// 0x429
	MANUAL_ENTITY_HARDCY_U,			// 0x42a
	MANUAL_ENTITY_YCY_U,			// 0x42b
	MANUAL_ENTITY_SOFTCY_U,			// 0x42c
	MANUAL_ENTITY_ECY_U,			// 0x42d
	MANUAL_ENTITY_YUCY_U,			// 0x42e
	MANUAL_ENTITY_YACY_U,			// 0x42f
	MANUAL_ENTITY_ACY_L,			// 0x430
	MANUAL_ENTITY_BCY_L,			// 0x431
	MANUAL_ENTITY_VCY_L,			// 0x432
	MANUAL_ENTITY_GCY_L,			// 0x433
	MANUAL_ENTITY_DCY_L,			// 0x434
	MANUAL_ENTITY_IECY_L,			// 0x435
	MANUAL_ENTITY_ZHCY_L,			// 0x436
	MANUAL_ENTITY_ZCY_L,			// 0x437
	MANUAL_ENTITY_ICY_L,			// 0x438
	MANUAL_ENTITY_JCY_L,			// 0x439
	MANUAL_ENTITY_KCY_L,			// 0x43a
	MANUAL_ENTITY_LCY_L,			// 0x43b
	MANUAL_ENTITY_MCY_L,			// 0x43c
	MANUAL_ENTITY_NCY_L,			// 0x43d
	MANUAL_ENTITY_OCY_L,			// 0x43e
	MANUAL_ENTITY_PCY_L,			// 0x43f
	MANUAL_ENTITY_RCY_L,			// 0x440
	MANUAL_ENTITY_SCY_L,			// 0x441
	MANUAL_ENTITY_TCY_L,			// 0x442
	MANUAL_ENTITY_UCY_L,			// 0x443
	MANUAL_ENTITY_FCY_L,			// 0x444
	MANUAL_ENTITY_KHCY_L,			// 0x445
	MANUAL_ENTITY_TSCY_L,			// 0x446
	MANUAL_ENTITY_CHCY_L,			// 0x447
	MANUAL_ENTITY_SHCY_L,			// 0x448
	MANUAL_ENTITY_SHCHCY_L,			// 0x449
	MANUAL_ENTITY_HARDCY_L,			// 0x44a
	MANUAL_ENTITY_YCY_L,			// 0x44b
	MANUAL_ENTITY_SOFTCY_L,			// 0x44c
	MANUAL_ENTITY_ECY_L,			// 0x44d
	MANUAL_ENTITY_YUCY_L,			// 0x44e
	MANUAL_ENTITY_YACY_L,			// 0x44f
	MANUAL_ENTITY_IOCY_L,			// 0x451
	MANUAL_ENTITY_DJCY_L,			// 0x452
	MANUAL_ENTITY_GJCY_L,			// 0x453
	MANUAL_ENTITY_JUKCY_L,			// 0x454
	MANUAL_ENTITY_DSCY_L,			// 0x455
	MANUAL_ENTITY_IUKCY_L,			// 0x456
	MANUAL_ENTITY_YICY_L,			// 0x457
	MANUAL_ENTITY_JSERCY_L,			// 0x458
	MANUAL_ENTITY_LJCY_L,			// 0x459
	MANUAL_ENTITY_NJCY_L,			// 0x45a
	MANUAL_ENTITY_TSHCY_L,			// 0x45b
	MANUAL_ENTITY_KJCY_L,			// 0x45c
	MANUAL_ENTITY_UBRCY_L,			// 0x45e
	MANUAL_ENTITY_DZCY_L,			// 0x45f

	/* General Punctuation */

	MANUAL_ENTITY_ENSP,			// 0x2002
	MANUAL_ENTITY_EMSP,			// 0x2003
	MANUAL_ENTITY_EMSP13,			// 0x2004
	MANUAL_ENTITY_EMSP14,			// 0x2005
	MANUAL_ENTITY_NUMSP,			// 0x2007
	MANUAL_ENTITY_PUNCSP,			// 0x2008
	MANUAL_ENTITY_THINSP,			// 0x2009
	MANUAL_ENTITY_VERYTHINSPACE,		// 0x200a
	MANUAL_ENTITY_NEGATIVEMEDIUMSPACE,	// 0x200b
	MANUAL_ENTITY_ZWNJ,			// 0x200c
	MANUAL_ENTITY_ZWJ,			// 0x200d
	MANUAL_ENTITY_LRM,			// 0x200e
	MANUAL_ENTITY_RLM,			// 0x200f
	MANUAL_ENTITY_DASH,			// 0x2010
	MANUAL_ENTITY_NDASH,			// 0x2013
	MANUAL_ENTITY_MDASH,			// 0x2014
	MANUAL_ENTITY_HORBAR,			// 0x2015
	MANUAL_ENTITY_VERBAR,			// 0x2016
	MANUAL_ENTITY_LSQUO,			// 0x2018
	MANUAL_ENTITY_RSQUO,			// 0x2019
	MANUAL_ENTITY_SBQUO,			// 0x201a
	MANUAL_ENTITY_LDQUO,			// 0x201c
	MANUAL_ENTITY_RDQUO,			// 0x201d
	MANUAL_ENTITY_BDQUO,			// 0x201e
	MANUAL_ENTITY_DAGGER,			// 0x2020
	MANUAL_ENTITY_DDAGGER,			// 0x2021
	MANUAL_ENTITY_BULL,			// 0x2022
	MANUAL_ENTITY_NLDR,			// 0x2025
	MANUAL_ENTITY_HELLIP,			// 0x2026
	MANUAL_ENTITY_PERMIL,			// 0x2030
	MANUAL_ENTITY_PERTENK,			// 0x2031
	MANUAL_ENTITY_PRIME,			// 0x2032
	MANUAL_ENTITY_DPRIME,			// 0x2033
	MANUAL_ENTITY_TPRIME,			// 0x2034
	MANUAL_ENTITY_BACKPRIME,		// 0x2035
	MANUAL_ENTITY_LSAQUO,			// 0x2039
	MANUAL_ENTITY_RSAQUO,			// 0x203a
	MANUAL_ENTITY_OLINE,			// 0x203e
	MANUAL_ENTITY_CARET,			// 0x2041
	MANUAL_ENTITY_HYBULL,			// 0x2043
	MANUAL_ENTITY_FRASL,			// 0x2044
	MANUAL_ENTITY_BSEMI,			// 0x204f
	MANUAL_ENTITY_QPRIME,			// 0x2057
	MANUAL_ENTITY_MEDIUMSPACE,		// 0x205f
	MANUAL_ENTITY_NOBREAK,			// 0x2060
	MANUAL_ENTITY_APPLYFUNCTION,		// 0x2061
	MANUAL_ENTITY_INVISIBLETIMES,		// 0x2062
	MANUAL_ENTITY_INVISIBLECOMMA,		// 0x2063

	/* Currency Symbols */

	MANUAL_ENTITY_EURO,			// 0x20ac

	/* Combining Diacritical Marks for Symbols */

	MANUAL_ENTITY_TRIPLEDOT,		// 0x20db
	MANUAL_ENTITY_DOTDOT,			// 0x20dc

	/* Letterlike Symbols */

	MANUAL_ENTITY_COPF_U,			// 0x2102
	MANUAL_ENTITY_INCARE,			// 0x2105
	MANUAL_ENTITY_GSCR_L,			// 0x210a
	MANUAL_ENTITY_HILBERTSPACE_U,		// 0x210b
	MANUAL_ENTITY_HFR_U,			// 0x210c
	MANUAL_ENTITY_HOPF_U,			// 0x210d
	MANUAL_ENTITY_PLANCKH_L,		// 0x210e
	MANUAL_ENTITY_HBAR_L,			// 0x210f
	MANUAL_ENTITY_ISCR_U,			// 0x2110
	MANUAL_ENTITY_IMAGE_U,			// 0x2111
	MANUAL_ENTITY_LAPLACETRF_U,		// 0x2112
	MANUAL_ENTITY_ELL_L,			// 0x2113
	MANUAL_ENTITY_NOPF_U,			// 0x2115
	MANUAL_ENTITY_NUMERO,			// 0x2116
	MANUAL_ENTITY_COPYSR,			// 0x2117
	MANUAL_ENTITY_WEIERP,			// 0x2118
	MANUAL_ENTITY_POPF_U,			// 0x2119
	MANUAL_ENTITY_QOPF_U,			// 0x211a
	MANUAL_ENTITY_RSCR_U,			// 0x211b
	MANUAL_ENTITY_REAL_U,			// 0x211c
	MANUAL_ENTITY_ROPF_U,			// 0x211d
	MANUAL_ENTITY_RX,			// 0x211e
	MANUAL_ENTITY_TRADE,			// 0x2122
	MANUAL_ENTITY_ZOPF_U,			// 0x2124
	MANUAL_ENTITY_MHO,			// 0x2127
	MANUAL_ENTITY_ZFR_U,			// 0x2128
	MANUAL_ENTITY_IIOTA,			// 0x2129
	MANUAL_ENTITY_BERNOULLIS_U,		// 0x212c
	MANUAL_ENTITY_CAYLEYS_U,		// 0x212d
	MANUAL_ENTITY_ESCR_L,			// 0x212f
	MANUAL_ENTITY_ESCR_U,			// 0x2130
	MANUAL_ENTITY_FOURIERTRF_U,		// 0x2131
	MANUAL_ENTITY_MELLINTRF_U,		// 0x2133
	MANUAL_ENTITY_ORDER_L,			// 0x2134
	MANUAL_ENTITY_ALEFSYM,			// 0x2135
	MANUAL_ENTITY_BETH,			// 0x2136
	MANUAL_ENTITY_GIMEL,			// 0x2137
	MANUAL_ENTITY_DALETH,			// 0x2138
	MANUAL_ENTITY_DIFFERENTIALD_U,		// 0x2145
	MANUAL_ENTITY_DIFFERENTIALD_L,		// 0x2146
	MANUAL_ENTITY_EXPONENTIALE_L,		// 0x2147
	MANUAL_ENTITY_IMAGINARYI_L,		// 0x2148

	/* Number Forms */

	MANUAL_ENTITY_FRAC13,			// 0x2153
	MANUAL_ENTITY_FRAC23,			// 0x2154
	MANUAL_ENTITY_FRAC15,			// 0x2155
	MANUAL_ENTITY_FRAC25,			// 0x2156
	MANUAL_ENTITY_FRAC35,			// 0x2157
	MANUAL_ENTITY_FRAC45,			// 0x2158
	MANUAL_ENTITY_FRAC16,			// 0x2159
	MANUAL_ENTITY_FRAC56,			// 0x215a
	MANUAL_ENTITY_FRAC18,			// 0x215b
	MANUAL_ENTITY_FRAC38,			// 0x215c
	MANUAL_ENTITY_FRAC58,			// 0x215d
	MANUAL_ENTITY_FRAC78,			// 0x215e

	/* Arrows */

	MANUAL_ENTITY_LARR,			// 0x2190
	MANUAL_ENTITY_UARR,			// 0x2191
	MANUAL_ENTITY_RARR,			// 0x2192
	MANUAL_ENTITY_DARR,			// 0x2193
	MANUAL_ENTITY_HARR,			// 0x2194
	MANUAL_ENTITY_UPDOWNARROW,		// 0x2195
	MANUAL_ENTITY_UPPERLEFTARROW,		// 0x2196
	MANUAL_ENTITY_UPPERRIGHTARROW,		// 0x2197
	MANUAL_ENTITY_LOWERRIGHTARROW,		// 0x2198
	MANUAL_ENTITY_LOWERLEFTARROW,		// 0x2199
	MANUAL_ENTITY_NLARR,			// 0x219a
	MANUAL_ENTITY_NRARR,			// 0x219b
	MANUAL_ENTITY_RARRW,			// 0x219d
	MANUAL_ENTITY_2HEADED_LARR,		// 0x219e
	MANUAL_ENTITY_2HEADED_UARR,		// 0x219f
	MANUAL_ENTITY_2HEADED_RARR,		// 0x21a0
	MANUAL_ENTITY_2HEADED_DARR,		// 0x21a1
	MANUAL_ENTITY_LARRTL,			// 0x21a2
	MANUAL_ENTITY_RARRTL,			// 0x21a3
	MANUAL_ENTITY_LEFTTEEARROW,		// 0x21a4
	MANUAL_ENTITY_UPTEEARROW,		// 0x21a5
	MANUAL_ENTITY_RIGHTTEEARROW,		// 0x21a6
	MANUAL_ENTITY_DOWNTEEARROW,		// 0x21a7
	MANUAL_ENTITY_HOOKLEFTARROW,		// 0x21a9
	MANUAL_ENTITY_HOOKRIGHTARROW,		// 0x21aa
	MANUAL_ENTITY_LARRLP,			// 0x21ab
	MANUAL_ENTITY_LOOPARROWRIGHT,		// 0x21ac
	MANUAL_ENTITY_HARRW,			// 0x21ad
	MANUAL_ENTITY_NHARR,			// 0x21ae
	MANUAL_ENTITY_LSH,			// 0x21b0
	MANUAL_ENTITY_RSH,			// 0x21b1
	MANUAL_ENTITY_LDSH,			// 0x21b2
	MANUAL_ENTITY_RDSH,			// 0x21b3
	MANUAL_ENTITY_CRARR,			// 0x21b5
	MANUAL_ENTITY_CULARR,			// 0x21b6
	MANUAL_ENTITY_CURARR,			// 0x21b7
	MANUAL_ENTITY_CIRCLEARROWLEFT,		// 0x21ba
	MANUAL_ENTITY_CIRCLEARROWRIGHT,		// 0x21bb
	MANUAL_ENTITY_LEFTVECTOR,		// 0x21bc
	MANUAL_ENTITY_DOWNLEFTVECTOR,		// 0x21bd
	MANUAL_ENTITY_RIGHTUPVECTOR,		// 0x21be
	MANUAL_ENTITY_LEFTUPVECTOR,		// 0x21bf
	MANUAL_ENTITY_RIGHTVECTOR,		// 0x21c0
	MANUAL_ENTITY_DOWNRIGHTVECTOR,		// 0x21c1
	MANUAL_ENTITY_RIGHTDOWNVECTOR,		// 0x21c2
	MANUAL_ENTITY_LEFTDOWNVECTOR,		// 0x21c3
	MANUAL_ENTITY_RIGHTARROWLEFTARROW,	// 0x21c4
	MANUAL_ENTITY_UPARROWDOWNARROW,		// 0x21c5
	MANUAL_ENTITY_LEFTARROWRIGHTARROW,	// 0x21c6
	MANUAL_ENTITY_LEFTLEFTARROWS,		// 0x21c7
	MANUAL_ENTITY_UPUPARROWS,		// 0x21c8
	MANUAL_ENTITY_RIGHTRIGHTARROWS,		// 0x21c9
	MANUAL_ENTITY_DDARR,			// 0x21ca
	MANUAL_ENTITY_REVERSEEQUILIBRIUM,	// 0x21cb
	MANUAL_ENTITY_EQUILIBRIUM,		// 0x21cc
	MANUAL_ENTITY_NLEFTARROW,		// 0x21cd
	MANUAL_ENTITY_NLEFTRIGHTARROW,		// 0x21ce
	MANUAL_ENTITY_NRIGHTARROW,		// 0x21cf
	MANUAL_ENTITY_DOUBLE_LARR,		// 0x21d0
	MANUAL_ENTITY_DOUBLE_UARR,		// 0x21d1
	MANUAL_ENTITY_DOUBLE_RARR,		// 0x21d2
	MANUAL_ENTITY_DOUBLE_DARR,		// 0x21d3
	MANUAL_ENTITY_DOUBLE_HARR,		// 0x21d4
	MANUAL_ENTITY_DOUBLEUPDOWNARROW,	// 0x21d5
	MANUAL_ENTITY_NWARR,			// 0x21d6
	MANUAL_ENTITY_NEARR,			// 0x21d7
	MANUAL_ENTITY_SEARR,			// 0x21d8
	MANUAL_ENTITY_SWARR,			// 0x21d9
	MANUAL_ENTITY_LLEFTARROW,		// 0x21da
	MANUAL_ENTITY_RRIGHTARROW,		// 0x21db
	MANUAL_ENTITY_ZIGRARR,			// 0x21dd
	MANUAL_ENTITY_LEFTARROWBAR,		// 0x21e4
	MANUAL_ENTITY_RIGHTARROWBAR,		// 0x21e5
	MANUAL_ENTITY_DOWNARROWUPARROW,		// 0x21f5
	MANUAL_ENTITY_LOARR,			// 0x21fd
	MANUAL_ENTITY_ROARR,			// 0x21fe
	MANUAL_ENTITY_HOARR,			// 0x21ff

	/* Mathematical Operators */

	MANUAL_ENTITY_FORALL,			// 0x2200
	MANUAL_ENTITY_COMP,			// 0x2201
	MANUAL_ENTITY_PART,			// 0x2202
	MANUAL_ENTITY_EXIST,			// 0x2203
	MANUAL_ENTITY_NOTEXISTS,		// 0x2204
	MANUAL_ENTITY_EMPTY,			// 0x2205
	MANUAL_ENTITY_NABLA,			// 0x2207
	MANUAL_ENTITY_ISIN,			// 0x2208
	MANUAL_ENTITY_NOTIN,			// 0x2209
	MANUAL_ENTITY_NI,			// 0x220b
	MANUAL_ENTITY_NOTREVERSEELEMENT,	// 0x220c
	MANUAL_ENTITY_PROD,			// 0x220f
	MANUAL_ENTITY_COPRODUCT,		// 0x2210
	MANUAL_ENTITY_SUM,			// 0x2211
	MANUAL_ENTITY_MINUS,			// 0x2212
	MANUAL_ENTITY_MINUSPLUS,		// 0x2213
	MANUAL_ENTITY_DOTPLUS,			// 0x2214
	MANUAL_ENTITY_BACKSLASH,		// 0x2216
	MANUAL_ENTITY_LOWAST,			// 0x2217
	MANUAL_ENTITY_SMALLCIRCLE,		// 0x2218
	MANUAL_ENTITY_RADIC,			// 0x221a
	MANUAL_ENTITY_PROP,			// 0x221d
	MANUAL_ENTITY_INFIN,			// 0x221e
	MANUAL_ENTITY_ANGRT,			// 0x221f
	MANUAL_ENTITY_ANG,			// 0x2220
	MANUAL_ENTITY_ANGMSD,			// 0x2221
	MANUAL_ENTITY_ANGSPH,			// 0x2222
	MANUAL_ENTITY_VERTICALBAR,		// 0x2223
	MANUAL_ENTITY_NOTVERTICALBAR,		// 0x2224
	MANUAL_ENTITY_DOUBLEVERTICALBAR,	// 0x2225
	MANUAL_ENTITY_NOTDOUBLEVERTICALBAR,	// 0x2226
	MANUAL_ENTITY_LOGICAL_AND,		// 0x2227
	MANUAL_ENTITY_LOGICAL_OR,		// 0x2228
	MANUAL_ENTITY_INTERSECTION,		// 0x2229
	MANUAL_ENTITY_UNION,			// 0x222a
	MANUAL_ENTITY_INTEGRAL,			// 0x222b
	MANUAL_ENTITY_DOUBLE_INTEGRAL,		// 0x222c
	MANUAL_ENTITY_TRIPLE_INTEGRAL,		// 0x222d
	MANUAL_ENTITY_CONTOURINTEGRAL,		// 0x222e
	MANUAL_ENTITY_CONINT,			// 0x222f
	MANUAL_ENTITY_CCONINT,			// 0x2230
	MANUAL_ENTITY_CWINT,			// 0x2231
	MANUAL_ENTITY_CLOCKWISECONTOURINTEGRAL,	// 0x2232
	MANUAL_ENTITY_COUNTERCLOCKWISECONTOURINTEGRAL,	// 0x2233
	MANUAL_ENTITY_THERE4,			// 0x2234
	MANUAL_ENTITY_BECAUSE,			// 0x2235
	MANUAL_ENTITY_RATIO,			// 0x2236
	MANUAL_ENTITY_PROPORTION,		// 0x2237
	MANUAL_ENTITY_DOTMINUS,			// 0x2238
	MANUAL_ENTITY_MDDOT,			// 0x223a
	MANUAL_ENTITY_HOMTHT,			// 0x223b
	MANUAL_ENTITY_SIM,			// 0x223c
	MANUAL_ENTITY_BACKSIM,			// 0x223d
	MANUAL_ENTITY_AC,			// 0x223e
	MANUAL_ENTITY_ACD,			// 0x223f
	MANUAL_ENTITY_VERTICALTILDE,		// 0x2240
	MANUAL_ENTITY_NOTTILDE,			// 0x2241
	MANUAL_ENTITY_EQUALTILDE,		// 0x2242
	MANUAL_ENTITY_TILDEEQUAL,		// 0x2243
	MANUAL_ENTITY_NOTTILDEEQUAL,		// 0x2244
	MANUAL_ENTITY_CONG,			// 0x2245
	MANUAL_ENTITY_SIMNE,			// 0x2246
	MANUAL_ENTITY_NOTTILDEFULLEQUAL,	// 0x2247
	MANUAL_ENTITY_ASYMP,			// 0x2248
	MANUAL_ENTITY_NOTTILDETILDE,		// 0x2249
	MANUAL_ENTITY_ALMOST_EQUAL_TO,		// 0x224a
	MANUAL_ENTITY_APID,			// 0x224b
	MANUAL_ENTITY_BACKCONG,			// 0x224c
	MANUAL_ENTITY_EQUIVALENT_TO,		// 0x224d
	MANUAL_ENTITY_BUMPEQ,			// 0x224e
	MANUAL_ENTITY_HUMPEQUAL,		// 0x224f
	MANUAL_ENTITY_DOTEQUAL,			// 0x2250
	MANUAL_ENTITY_DOTEQDOT,			// 0x2251
	MANUAL_ENTITY_EFDOT,			// 0x2252
	MANUAL_ENTITY_ERDOT,			// 0x2253
	MANUAL_ENTITY_ASSIGN,			// 0x2254
	MANUAL_ENTITY_ECOLON,			// 0x2255
	MANUAL_ENTITY_ECIR,			// 0x2256
	MANUAL_ENTITY_CIRCEQ,			// 0x2257
	MANUAL_ENTITY_WEDGEQ,			// 0x2259
	MANUAL_ENTITY_VEEEQ,			// 0x225a
	MANUAL_ENTITY_TRIANGLEQ,		// 0x225c
	MANUAL_ENTITY_EQUEST,			// 0x225f
	MANUAL_ENTITY_NE,			// 0x2260
	MANUAL_ENTITY_EQUIV,			// 0x2261
	MANUAL_ENTITY_NOTCONGRUENT,		// 0x2262
	MANUAL_ENTITY_LE,			// 0x2264
	MANUAL_ENTITY_GE,			// 0x2265
	MANUAL_ENTITY_LESSFULLEQUAL,		// 0x2266
	MANUAL_ENTITY_GREATERFULLEQUAL,		// 0x2267
	MANUAL_ENTITY_LTNE,			// 0x2268
	MANUAL_ENTITY_GTNE,			// 0x2269
	MANUAL_ENTITY_MUCH_LT,			// 0x226a
	MANUAL_ENTITY_MUCH_GT,			// 0x226b
	MANUAL_ENTITY_BETWEEN,			// 0x226c
	MANUAL_ENTITY_NOTCUPCAP,		// 0x226d
	MANUAL_ENTITY_NOTLESS,			// 0x226e
	MANUAL_ENTITY_NOTGREATER,		// 0x226f
	MANUAL_ENTITY_NOTLESSEQUAL,		// 0x2270
	MANUAL_ENTITY_NOTGREATEREQUAL,		// 0x2271
	MANUAL_ENTITY_LESSTILDE,		// 0x2272
	MANUAL_ENTITY_GREATERTILDE,		// 0x2273
	MANUAL_ENTITY_NOTLESSTILDE,		// 0x2274
	MANUAL_ENTITY_NOTGREATERTILDE,		// 0x2275
	MANUAL_ENTITY_LESSGREATER,		// 0x2276
	MANUAL_ENTITY_GREATERLESS,		// 0x2277
	MANUAL_ENTITY_NOTLESSGREATER,		// 0x2278
	MANUAL_ENTITY_NOTGREATERLESS,		// 0x2279
	MANUAL_ENTITY_PRECEDES,			// 0x227a
	MANUAL_ENTITY_SUCCEEDS,			// 0x227b
	MANUAL_ENTITY_PRECEDESSLANTEQUAL,	// 0x227c
	MANUAL_ENTITY_SUCCEEDSSLANTEQUAL,	// 0x227d
	MANUAL_ENTITY_PRECEDESTILDE,		// 0x227e
	MANUAL_ENTITY_SUCCEEDSTILDE,		// 0x227f
	MANUAL_ENTITY_NOTPRECEDES,		// 0x2280
	MANUAL_ENTITY_NOTSUCCEEDS,		// 0x2281
	MANUAL_ENTITY_SUBSET_OF,		// 0x2282
	MANUAL_ENTITY_SUPERSET_OF,		// 0x2283
	MANUAL_ENTITY_NSUB,			// 0x2284
	MANUAL_ENTITY_NSUP,			// 0x2285
	MANUAL_ENTITY_SUBSET_OF_EQ,		// 0x2286
	MANUAL_ENTITY_SUPERSET_OF_EQ,		// 0x2287
	MANUAL_ENTITY_NOTSUBSETEQUAL,		// 0x2288
	MANUAL_ENTITY_NOTSUPERSETEQUAL,		// 0x2289
	MANUAL_ENTITY_SUBSET_OF_NE,		// 0x228a
	MANUAL_ENTITY_SUPERSET_OF_NE,		// 0x228b
	MANUAL_ENTITY_CUPDOT,			// 0x228d
	MANUAL_ENTITY_UNIONPLUS,		// 0x228e
	MANUAL_ENTITY_SQUARESUBSET,		// 0x228f
	MANUAL_ENTITY_SQUARESUPERSET,		// 0x2290
	MANUAL_ENTITY_SQUARESUBSETEQUAL,	// 0x2291
	MANUAL_ENTITY_SQUARESUPERSETEQUAL,	// 0x2292
	MANUAL_ENTITY_SQUAREINTERSECTION,	// 0x2293
	MANUAL_ENTITY_SQUAREUNION,		// 0x2294
	MANUAL_ENTITY_OPLUS,			// 0x2295
	MANUAL_ENTITY_CIRCLEMINUS,		// 0x2296
	MANUAL_ENTITY_CIRCLETIMES,		// 0x2297
	MANUAL_ENTITY_OSOL,			// 0x2298
	MANUAL_ENTITY_CIRCLEDOT,		// 0x2299
	MANUAL_ENTITY_CIRCLEDCIRC,		// 0x229a
	MANUAL_ENTITY_CIRCLEDAST,		// 0x229b
	MANUAL_ENTITY_CIRCLEDDASH,		// 0x229d
	MANUAL_ENTITY_BOXPLUS,			// 0x229e
	MANUAL_ENTITY_BOXMINUS,			// 0x229f
	MANUAL_ENTITY_BOXTIMES,			// 0x22a0
	MANUAL_ENTITY_DOTSQUARE,		// 0x22a1
	MANUAL_ENTITY_RIGHTTEE,			// 0x22a2
	MANUAL_ENTITY_LEFTTEE,			// 0x22a3
	MANUAL_ENTITY_DOWNTEE,			// 0x22a4
	MANUAL_ENTITY_PERP,			// 0x22a5
	MANUAL_ENTITY_MODELS,			// 0x22a7
	MANUAL_ENTITY_DOUBLERIGHTTEE,		// 0x22a8
	MANUAL_ENTITY_VDASH,			// 0x22a9
	MANUAL_ENTITY_VVDASH,			// 0x22aa
	MANUAL_ENTITY_DVB_DRT,			// 0x22ab
	MANUAL_ENTITY_N_SVB_SRT,		// 0x22ac
	MANUAL_ENTITY_N_SVB_DRT,		// 0x22ad
	MANUAL_ENTITY_N_DVB_SRT,		// 0x22ae
	MANUAL_ENTITY_N_DVB_DRT,		// 0x22af
	MANUAL_ENTITY_PRUREL,			// 0x22b0
	MANUAL_ENTITY_LEFTTRIANGLE,		// 0x22b2
	MANUAL_ENTITY_RIGHTTRIANGLE,		// 0x22b3
	MANUAL_ENTITY_LEFTTRIANGLEEQUAL,	// 0x22b4
	MANUAL_ENTITY_RIGHTTRIANGLEEQUAL,	// 0x22b5
	MANUAL_ENTITY_ORIGOF,			// 0x22b6
	MANUAL_ENTITY_IMOF,			// 0x22b7
	MANUAL_ENTITY_MULTIMAP,			// 0x22b8
	MANUAL_ENTITY_HERCON,			// 0x22b9
	MANUAL_ENTITY_INTCAL,			// 0x22ba
	MANUAL_ENTITY_VEEBAR,			// 0x22bb
	MANUAL_ENTITY_BARVEE,			// 0x22bd
	MANUAL_ENTITY_ANGRTVB,			// 0x22be
	MANUAL_ENTITY_LRTRI,			// 0x22bf
	MANUAL_ENTITY_WEDGE,			// 0x22c0
	MANUAL_ENTITY_VEE,			// 0x22c1
	MANUAL_ENTITY_NARY_INTERSECTION,	// 0x22c2
	MANUAL_ENTITY_NARY_UNION,		// 0x22c3
	MANUAL_ENTITY_DIAMOND,			// 0x22c4
	MANUAL_ENTITY_SDOT,			// 0x22c5
	MANUAL_ENTITY_STAR_OPERATOR,		// 0x22c6
	MANUAL_ENTITY_DIVIDEONTIMES,		// 0x22c7
	MANUAL_ENTITY_BOWTIE,			// 0x22c8
	MANUAL_ENTITY_LTIMES,			// 0x22c9
	MANUAL_ENTITY_RTIMES,			// 0x22ca
	MANUAL_ENTITY_LEFTTHREETIMES,		// 0x22cb
	MANUAL_ENTITY_RIGHTTHREETIMES,		// 0x22cc
	MANUAL_ENTITY_BACKSIMEQ,		// 0x22cd
	MANUAL_ENTITY_CURLYVEE,			// 0x22ce
	MANUAL_ENTITY_CURLYWEDGE,		// 0x22cf
	MANUAL_ENTITY_DOUBLE_SUBSET,		// 0x22d0
	MANUAL_ENTITY_DOUBLE_SUPERSET,		// 0x22d1
	MANUAL_ENTITY_DOUBLE_INTERSECTION,	// 0x22d2
	MANUAL_ENTITY_DOUBLE_UNION,		// 0x22d3
	MANUAL_ENTITY_FORK,			// 0x22d4
	MANUAL_ENTITY_EPAR,			// 0x22d5
	MANUAL_ENTITY_LESSDOT,			// 0x22d6
	MANUAL_ENTITY_GTDOT,			// 0x22d7
	MANUAL_ENTITY_LL,			// 0x22d8
	MANUAL_ENTITY_GG,			// 0x22d9
	MANUAL_ENTITY_LESSEQUALGREATER,		// 0x22da
	MANUAL_ENTITY_GREATEREQUALLESS,		// 0x22db
	MANUAL_ENTITY_CUEPR,			// 0x22de
	MANUAL_ENTITY_CUESC,			// 0x22df
	MANUAL_ENTITY_NOTPRECEDESSLANTEQUAL,	// 0x22e0
	MANUAL_ENTITY_NOTSUCCEEDSSLANTEQUAL,	// 0x22e1
	MANUAL_ENTITY_NOTSQUARESUBSETEQUAL,	// 0x22e2
	MANUAL_ENTITY_NOTSQUARESUPERSETEQUAL,	// 0x22e3
	MANUAL_ENTITY_LNSIM,			// 0x22e6
	MANUAL_ENTITY_GNSIM,			// 0x22e7
	MANUAL_ENTITY_PRECNSIM,			// 0x22e8
	MANUAL_ENTITY_SCNSIM,			// 0x22e9
	MANUAL_ENTITY_NOTLEFTTRIANGLE,		// 0x22ea
	MANUAL_ENTITY_NOTRIGHTTRIANGLE,		// 0x22eb
	MANUAL_ENTITY_NOTLEFTTRIANGLEEQUAL,	// 0x22ec
	MANUAL_ENTITY_NOTRIGHTTRIANGLEEQUAL,	// 0x22ed
	MANUAL_ENTITY_VELLIP,			// 0x22ee
	MANUAL_ENTITY_CTDOT,			// 0x22ef
	MANUAL_ENTITY_UTDOT,			// 0x22f0
	MANUAL_ENTITY_DTDOT,			// 0x22f1
	MANUAL_ENTITY_DISIN,			// 0x22f2
	MANUAL_ENTITY_ISINSV,			// 0x22f3
	MANUAL_ENTITY_ISINS,			// 0x22f4
	MANUAL_ENTITY_ISINDOT,			// 0x22f5
	MANUAL_ENTITY_NOTINVC,			// 0x22f6
	MANUAL_ENTITY_NOTINVB,			// 0x22f7
	MANUAL_ENTITY_ISINE,			// 0x22f9
	MANUAL_ENTITY_NISD,			// 0x22fa
	MANUAL_ENTITY_XNIS,			// 0x22fb
	MANUAL_ENTITY_NIS,			// 0x22fc
	MANUAL_ENTITY_NOTNIVC,			// 0x22fd
	MANUAL_ENTITY_NOTNIVB,			// 0x22fe

	/* Miscellaneous Technical */

	MANUAL_ENTITY_BARWEDGE,			// 0x2305
	MANUAL_ENTITY_DOUBLE_BARWEDGE,		// 0x2306
	MANUAL_ENTITY_LCEIL,			// 0x2308
	MANUAL_ENTITY_RCEIL,			// 0x2309
	MANUAL_ENTITY_LFLOOR,			// 0x230a
	MANUAL_ENTITY_RFLOOR,			// 0x230b
	MANUAL_ENTITY_DRCROP,			// 0x230c
	MANUAL_ENTITY_DLCROP,			// 0x230d
	MANUAL_ENTITY_URCROP,			// 0x230e
	MANUAL_ENTITY_ULCROP,			// 0x230f
	MANUAL_ENTITY_REVERSED_NOT,		// 0x2310
	MANUAL_ENTITY_PROFLINE,			// 0x2312
	MANUAL_ENTITY_PROFSURF,			// 0x2313
	MANUAL_ENTITY_TELREC,			// 0x2315
	MANUAL_ENTITY_TARGET,			// 0x2316
	MANUAL_ENTITY_ULCORN,			// 0x231c
	MANUAL_ENTITY_URCORN,			// 0x231d
	MANUAL_ENTITY_DLCORN,			// 0x231e
	MANUAL_ENTITY_DRCORN,			// 0x231f
	MANUAL_ENTITY_FROWN,			// 0x2322
	MANUAL_ENTITY_SMILE,			// 0x2323
	MANUAL_ENTITY_LANGLE_BRACKET,		// 0x2329
	MANUAL_ENTITY_RANGLE_BRACKET,		// 0x232a
	MANUAL_ENTITY_CYLCTY,			// 0x232d
	MANUAL_ENTITY_PROFALAR,			// 0x232e
	MANUAL_ENTITY_TOPBOT,			// 0x2336
	MANUAL_ENTITY_OVBAR,			// 0x233d
	MANUAL_ENTITY_SOLBAR,			// 0x233f
	MANUAL_ENTITY_ANGZARR,			// 0x237c
	MANUAL_ENTITY_LMOUST,			// 0x23b0
	MANUAL_ENTITY_RMOUST,			// 0x23b1
	MANUAL_ENTITY_OVERBRACKET,		// 0x23b4
	MANUAL_ENTITY_UNDERBRACKET,		// 0x23b5
	MANUAL_ENTITY_BBRKTBRK,			// 0x23b6
	MANUAL_ENTITY_OVERPARENTHESIS,		// 0x23dc
	MANUAL_ENTITY_UNDERPARENTHESIS,		// 0x23dd
	MANUAL_ENTITY_OVERBRACE,		// 0x23de
	MANUAL_ENTITY_UNDERBRACE,		// 0x23df
	MANUAL_ENTITY_TRPEZIUM,			// 0x23e2
	MANUAL_ENTITY_ELINTERS,			// 0x23e7

	/* Control Pictures */

	MANUAL_ENTITY_BLANK,			// 0x2423

	/* Enclosed Alphanumerics */

	MANUAL_ENTITY_CIRCLEDS_U,		// 0x24c8

	/* Box Drawing */

	MANUAL_ENTITY_HORIZONTALLINE,		// 0x2500
	MANUAL_ENTITY_BOX_V,			// 0x2502
	MANUAL_ENTITY_BOX_D_R,			// 0x250c
	MANUAL_ENTITY_BOX_D_L,			// 0x2510
	MANUAL_ENTITY_BOX_U_R,			// 0x2514
	MANUAL_ENTITY_BOX_U_L,			// 0x2518
	MANUAL_ENTITY_BOX_V_R,			// 0x251c
	MANUAL_ENTITY_BOX_V_L,			// 0x2524
	MANUAL_ENTITY_BOX_H_D,			// 0x252c
	MANUAL_ENTITY_BOX_H_U,			// 0x2534
	MANUAL_ENTITY_BOX_V_H,			// 0x253c
	MANUAL_ENTITY_BOX_H,			// 0x2550
	MANUAL_ENTITY_BOX_VV,			// 0x2551
	MANUAL_ENTITY_BOX_D_RR,			// 0x2552
	MANUAL_ENTITY_BOX_DD_R,			// 0x2553
	MANUAL_ENTITY_BOX_DD_RR,		// 0x2554
	MANUAL_ENTITY_BOX_D_LL,			// 0x2555
	MANUAL_ENTITY_BOX_DD_L,			// 0x2556
	MANUAL_ENTITY_BOX_DD_LL,		// 0x2557
	MANUAL_ENTITY_BOX_U_RR,			// 0x2558
	MANUAL_ENTITY_BOX_UU_R,			// 0x2559
	MANUAL_ENTITY_BOX_UU_RR,		// 0x255a
	MANUAL_ENTITY_BOX_U_LL,			// 0x255b
	MANUAL_ENTITY_BOX_UU_L,			// 0x255c
	MANUAL_ENTITY_BOX_UU_LL,		// 0x255d
	MANUAL_ENTITY_BOX_V_RR,			// 0x255e
	MANUAL_ENTITY_BOX_VV_R,			// 0x255f
	MANUAL_ENTITY_BOX_VV_RR,		// 0x2560
	MANUAL_ENTITY_BOX_V_LL,			// 0x2561
	MANUAL_ENTITY_BOX_VV_L,			// 0x2562
	MANUAL_ENTITY_BOX_VV_LL,		// 0x2563
	MANUAL_ENTITY_BOX_HH_D,			// 0x2564
	MANUAL_ENTITY_BOX_H_DD,			// 0x2565
	MANUAL_ENTITY_BOX_HH_DD,		// 0x2566
	MANUAL_ENTITY_BOX_HH_U,			// 0x2567
	MANUAL_ENTITY_BOX_H_UU,			// 0x2568
	MANUAL_ENTITY_BOX_HH_UU,		// 0x2569
	MANUAL_ENTITY_BOX_V_HH,			// 0x256a
	MANUAL_ENTITY_BOX_VV_H,			// 0x256b
	MANUAL_ENTITY_BOX_VV_HH,		// 0x256c

	/* Block Elements */

	MANUAL_ENTITY_UHBLK,			// 0x2580
	MANUAL_ENTITY_LHBLK,			// 0x2584
	MANUAL_ENTITY_BLOCK,			// 0x2588
	MANUAL_ENTITY_BLK14,			// 0x2591
	MANUAL_ENTITY_BLK12,			// 0x2592
	MANUAL_ENTITY_BLK34,			// 0x2593

	/* Geometric Shapes */

	MANUAL_ENTITY_SQUARE,			// 0x25a1
	MANUAL_ENTITY_FILLEDVERYSMALLSQUARE,	// 0x25aa
	MANUAL_ENTITY_EMPTYVERYSMALLSQUARE,	// 0x25ab
	MANUAL_ENTITY_RECT,			// 0x25ad
	MANUAL_ENTITY_MARKER,			// 0x25ae
	MANUAL_ENTITY_FLTNS,			// 0x25b1
	MANUAL_ENTITY_BIGTRIANGLEUP,		// 0x25b3
	MANUAL_ENTITY_BLACKTRIANGLE,		// 0x25b4
	MANUAL_ENTITY_TRIANGLE,			// 0x25b5
	MANUAL_ENTITY_BLACKTRIANGLERIGHT,	// 0x25b8
	MANUAL_ENTITY_RTRI,			// 0x25b9
	MANUAL_ENTITY_BIGTRIANGLEDOWN,		// 0x25bd
	MANUAL_ENTITY_BLACKTRIANGLEDOWN,	// 0x25be
	MANUAL_ENTITY_DTRI,			// 0x25bf
	MANUAL_ENTITY_BLACKTRIANGLELEFT,	// 0x25c2
	MANUAL_ENTITY_LTRI,			// 0x25c3
	MANUAL_ENTITY_LOZ,			// 0x25ca
	MANUAL_ENTITY_CIR,			// 0x25cb
	MANUAL_ENTITY_TRIDOT,			// 0x25ec
	MANUAL_ENTITY_BIGCIRC,			// 0x25ef
	MANUAL_ENTITY_ULTRI,			// 0x25f8
	MANUAL_ENTITY_URTRI,			// 0x25f9
	MANUAL_ENTITY_LLTRI,			// 0x25fa
	MANUAL_ENTITY_EMPTYSMALLSQUARE,		// 0x25fb
	MANUAL_ENTITY_FILLEDSMALLSQUARE,	// 0x25fc

	/* Miscellaneous Symbols */

	MANUAL_ENTITY_BIGSTAR,			// 0x2605
	MANUAL_ENTITY_STAR,			// 0x2606
	MANUAL_ENTITY_PHONE,			// 0x260e
	MANUAL_ENTITY_FEMALE,			// 0x2640
	MANUAL_ENTITY_MALE,			// 0x2642
	MANUAL_ENTITY_SPADES,			// 0x2660
	MANUAL_ENTITY_CLUBS,			// 0x2663
	MANUAL_ENTITY_HEARTS,			// 0x2665
	MANUAL_ENTITY_DIAMS,			// 0x2666
	MANUAL_ENTITY_SUNG,			// 0x266a
	MANUAL_ENTITY_FLAT,			// 0x266d
	MANUAL_ENTITY_NATUR,			// 0x266e
	MANUAL_ENTITY_SHARP,			// 0x266f

	/* Dingbats */

	MANUAL_ENTITY_CHECK,			// 0x2713
	MANUAL_ENTITY_CROSS,			// 0x2717
	MANUAL_ENTITY_MALT,			// 0x2720
	MANUAL_ENTITY_SEXT,			// 0x2736
	MANUAL_ENTITY_VERTICALSEPARATOR,	// 0x2758
	MANUAL_ENTITY_LBBRK,			// 0x2772
	MANUAL_ENTITY_RBBRK,			// 0x2773

	/* Miscellaneous Mathematical Symbols-A */

	MANUAL_ENTITY_BSOLHSUB,			// 0x27c8
	MANUAL_ENTITY_SUPHSOL,			// 0x27c9
	MANUAL_ENTITY_LEFTDOUBLEBRACKET,	// 0x27e6
	MANUAL_ENTITY_RIGHTDOUBLEBRACKET,	// 0x27e7
	MANUAL_ENTITY_LEFTANGLEBRACKET,		// 0x27e8
	MANUAL_ENTITY_RIGHTANGLEBRACKET,	// 0x27e9
	MANUAL_ENTITY_LDOUBLE_ANGLE_BRACKET,	// 0x27ea
	MANUAL_ENTITY_RDOUBLE_ANGLE_BRACKET,	// 0x27eb
	MANUAL_ENTITY_LOANG,			// 0x27ec
	MANUAL_ENTITY_ROANG,			// 0x27ed

	/* Supplemental Arrows-A */

	MANUAL_ENTITY_LONGLEFTARROW,		// 0x27f5
	MANUAL_ENTITY_LONGRIGHTARROW,		// 0x27f6
	MANUAL_ENTITY_LONGLEFTRIGHTARROW,	// 0x27f7
	MANUAL_ENTITY_DOUBLELONGLEFTARROW,	// 0x27f8
	MANUAL_ENTITY_DOUBLELONGRIGHTARROW,	// 0x27f9
	MANUAL_ENTITY_DOUBLELONGLEFTRIGHTARROW,	// 0x27fa
	MANUAL_ENTITY_LONGMAPSTO,		// 0x27fc
	MANUAL_ENTITY_DZIGRARR,			// 0x27ff

	/* Supplemental Arrows-B */

	MANUAL_ENTITY_NVLARR,			// 0x2902
	MANUAL_ENTITY_NVRARR,			// 0x2903
	MANUAL_ENTITY_NVHARR,			// 0x2904
	MANUAL_ENTITY_MAP,			// 0x2905
	MANUAL_ENTITY_LBARR,			// 0x290c
	MANUAL_ENTITY_BKAROW,			// 0x290d
	MANUAL_ENTITY_DLBARR,			// 0x290e
	MANUAL_ENTITY_DBKAROW,			// 0x290f
	MANUAL_ENTITY_RBARR,			// 0x2910
	MANUAL_ENTITY_DDOTRAHD,			// 0x2911
	MANUAL_ENTITY_UPARROWBAR,		// 0x2912
	MANUAL_ENTITY_DOWNARROWBAR,		// 0x2913
	MANUAL_ENTITY_RRARRTL,			// 0x2916
	MANUAL_ENTITY_LATAIL,			// 0x2919
	MANUAL_ENTITY_RATAIL,			// 0x291a
	MANUAL_ENTITY_DLATAIL,			// 0x291b
	MANUAL_ENTITY_DRATAIL,			// 0x291c
	MANUAL_ENTITY_LARRFS,			// 0x291d
	MANUAL_ENTITY_RARRFS,			// 0x291e
	MANUAL_ENTITY_LARRBFS,			// 0x291f
	MANUAL_ENTITY_RARRBFS,			// 0x2920
	MANUAL_ENTITY_NWARHK,			// 0x2923
	MANUAL_ENTITY_NEARHK,			// 0x2924
	MANUAL_ENTITY_HKSEAROW,			// 0x2925
	MANUAL_ENTITY_HKSWAROW,			// 0x2926
	MANUAL_ENTITY_NWNEAR,			// 0x2927
	MANUAL_ENTITY_NESEAR,			// 0x2928
	MANUAL_ENTITY_SESWAR,			// 0x2929
	MANUAL_ENTITY_SWNWAR,			// 0x292a
	MANUAL_ENTITY_RARRC,			// 0x2933
	MANUAL_ENTITY_CUDARRR,			// 0x2935
	MANUAL_ENTITY_LDCA,			// 0x2936
	MANUAL_ENTITY_RDCA,			// 0x2937
	MANUAL_ENTITY_CUDARRL,			// 0x2938
	MANUAL_ENTITY_LARRPL,			// 0x2939
	MANUAL_ENTITY_CURARRM,			// 0x293c
	MANUAL_ENTITY_CULARRP,			// 0x293d
	MANUAL_ENTITY_RARRPL,			// 0x2945
	MANUAL_ENTITY_HARRCIR,			// 0x2948
	MANUAL_ENTITY_UARROCIR,			// 0x2949
	MANUAL_ENTITY_LURDSHAR,			// 0x294a
	MANUAL_ENTITY_LDRUSHAR,			// 0x294b
	MANUAL_ENTITY_LEFTRIGHTVECTOR,		// 0x294e
	MANUAL_ENTITY_RIGHTUPDOWNVECTOR,	// 0x294f
	MANUAL_ENTITY_DOWNLEFTRIGHTVECTOR,	// 0x2950
	MANUAL_ENTITY_LEFTUPDOWNVECTOR,		// 0x2951
	MANUAL_ENTITY_LEFTVECTORBAR,		// 0x2952
	MANUAL_ENTITY_RIGHTVECTORBAR,		// 0x2953
	MANUAL_ENTITY_RIGHTUPVECTORBAR,		// 0x2954
	MANUAL_ENTITY_RIGHTDOWNVECTORBAR,	// 0x2955
	MANUAL_ENTITY_DOWNLEFTVECTORBAR,	// 0x2956
	MANUAL_ENTITY_DOWNRIGHTVECTORBAR,	// 0x2957
	MANUAL_ENTITY_LEFTUPVECTORBAR,		// 0x2958
	MANUAL_ENTITY_LEFTDOWNVECTORBAR,	// 0x2959
	MANUAL_ENTITY_LEFTTEEVECTOR,		// 0x295a
	MANUAL_ENTITY_RIGHTTEEVECTOR,		// 0x295b
	MANUAL_ENTITY_RIGHTUPTEEVECTOR,		// 0x295c
	MANUAL_ENTITY_RIGHTDOWNTEEVECTOR,	// 0x295d
	MANUAL_ENTITY_DOWNLEFTTEEVECTOR,	// 0x295e
	MANUAL_ENTITY_DOWNRIGHTTEEVECTOR,	// 0x295f
	MANUAL_ENTITY_LEFTUPTEEVECTOR,		// 0x2960
	MANUAL_ENTITY_LEFTDOWNTEEVECTOR,	// 0x2961
	MANUAL_ENTITY_LHAR,			// 0x2962
	MANUAL_ENTITY_UHAR,			// 0x2963
	MANUAL_ENTITY_RHAR,			// 0x2964
	MANUAL_ENTITY_DHAR,			// 0x2965
	MANUAL_ENTITY_LURUHAR,			// 0x2966
	MANUAL_ENTITY_LDRDHAR,			// 0x2967
	MANUAL_ENTITY_RULUHAR,			// 0x2968
	MANUAL_ENTITY_RDLDHAR,			// 0x2969
	MANUAL_ENTITY_LHARUL,			// 0x296a
	MANUAL_ENTITY_LLHARD,			// 0x296b
	MANUAL_ENTITY_RHARUL,			// 0x296c
	MANUAL_ENTITY_LRHARD,			// 0x296d
	MANUAL_ENTITY_UPEQUILIBRIUM,		// 0x296e
	MANUAL_ENTITY_REVERSEUPEQUILIBRIUM,	// 0x296f
	MANUAL_ENTITY_ROUNDIMPLIES,		// 0x2970
	MANUAL_ENTITY_ERARR,			// 0x2971
	MANUAL_ENTITY_SIMRARR,			// 0x2972
	MANUAL_ENTITY_LARRSIM,			// 0x2973
	MANUAL_ENTITY_RARRSIM,			// 0x2974
	MANUAL_ENTITY_RARRAP,			// 0x2975
	MANUAL_ENTITY_LTLARR,			// 0x2976
	MANUAL_ENTITY_GTRARR,			// 0x2978
	MANUAL_ENTITY_SUBRARR,			// 0x2979
	MANUAL_ENTITY_SUPLARR,			// 0x297b
	MANUAL_ENTITY_LFISHT,			// 0x297c
	MANUAL_ENTITY_RFISHT,			// 0x297d
	MANUAL_ENTITY_UFISHT,			// 0x297e
	MANUAL_ENTITY_DFISHT,			// 0x297f

	/* Miscellaneous Mathematical Symbols-B */

	MANUAL_ENTITY_LOPAR,			// 0x2985
	MANUAL_ENTITY_ROPAR,			// 0x2986
	MANUAL_ENTITY_LBRKE,			// 0x298b
	MANUAL_ENTITY_RBRKE,			// 0x298c
	MANUAL_ENTITY_LBRKSLU,			// 0x298d
	MANUAL_ENTITY_RBRKSLD,			// 0x298e
	MANUAL_ENTITY_LBRKSLD,			// 0x298f
	MANUAL_ENTITY_RBRKSLU,			// 0x2990
	MANUAL_ENTITY_LANGD,			// 0x2991
	MANUAL_ENTITY_RANGD,			// 0x2992
	MANUAL_ENTITY_LPARLT,			// 0x2993
	MANUAL_ENTITY_RPARGT,			// 0x2994
	MANUAL_ENTITY_GTLPAR,			// 0x2995
	MANUAL_ENTITY_LTRPAR,			// 0x2996
	MANUAL_ENTITY_VZIGZAG,			// 0x299a
	MANUAL_ENTITY_VANGRT,			// 0x299c
	MANUAL_ENTITY_ANGRTVBD,			// 0x299d
	MANUAL_ENTITY_ANGE,			// 0x29a4
	MANUAL_ENTITY_RANGE,			// 0x29a5
	MANUAL_ENTITY_DWANGLE,			// 0x29a6
	MANUAL_ENTITY_UWANGLE,			// 0x29a7
	MANUAL_ENTITY_ANGMSDAA,			// 0x29a8
	MANUAL_ENTITY_ANGMSDAB,			// 0x29a9
	MANUAL_ENTITY_ANGMSDAC,			// 0x29aa
	MANUAL_ENTITY_ANGMSDAD,			// 0x29ab
	MANUAL_ENTITY_ANGMSDAE,			// 0x29ac
	MANUAL_ENTITY_ANGMSDAF,			// 0x29ad
	MANUAL_ENTITY_ANGMSDAG,			// 0x29ae
	MANUAL_ENTITY_ANGMSDAH,			// 0x29af
	MANUAL_ENTITY_BEMPTYV,			// 0x29b0
	MANUAL_ENTITY_DEMPTYV,			// 0x29b1
	MANUAL_ENTITY_CEMPTYV,			// 0x29b2
	MANUAL_ENTITY_RAEMPTYV,			// 0x29b3
	MANUAL_ENTITY_LAEMPTYV,			// 0x29b4
	MANUAL_ENTITY_OHBAR,			// 0x29b5
	MANUAL_ENTITY_OMID,			// 0x29b6
	MANUAL_ENTITY_OPAR,			// 0x29b7
	MANUAL_ENTITY_OPERP,			// 0x29b9
	MANUAL_ENTITY_OLCROSS,			// 0x29bb
	MANUAL_ENTITY_ODSOLD,			// 0x29bc
	MANUAL_ENTITY_OLCIR,			// 0x29be
	MANUAL_ENTITY_OFCIR,			// 0x29bf
	MANUAL_ENTITY_OLT,			// 0x29c0
	MANUAL_ENTITY_OGT,			// 0x29c1
	MANUAL_ENTITY_CIRSCIR,			// 0x29c2
	MANUAL_ENTITY_CIRE,			// 0x29c3
	MANUAL_ENTITY_SOLB,			// 0x29c4
	MANUAL_ENTITY_BSOLB,			// 0x29c5
	MANUAL_ENTITY_BOXBOX,			// 0x29c9
	MANUAL_ENTITY_TRISB,			// 0x29cd
	MANUAL_ENTITY_RTRILTRI,			// 0x29ce
	MANUAL_ENTITY_LEFTTRIANGLEBAR,		// 0x29cf
	MANUAL_ENTITY_RIGHTTRIANGLEBAR,		// 0x29d0
	MANUAL_ENTITY_IINFIN,			// 0x29dc
	MANUAL_ENTITY_INFINTIE,			// 0x29dd
	MANUAL_ENTITY_NVINFIN,			// 0x29de
	MANUAL_ENTITY_EPARSL,			// 0x29e3
	MANUAL_ENTITY_SMEPARSL,			// 0x29e4
	MANUAL_ENTITY_EQVPARSL,			// 0x29e5
	MANUAL_ENTITY_BLACKLOZENGE,		// 0x29eb
	MANUAL_ENTITY_RULEDELAYED,		// 0x29f4
	MANUAL_ENTITY_DSOL,			// 0x29f6

	/* Supplemental Mathematical Operators */

	MANUAL_ENTITY_BIGODOT,			// 0x2a00
	MANUAL_ENTITY_BIGOPLUS,			// 0x2a01
	MANUAL_ENTITY_BIGOTIMES,		// 0x2a02
	MANUAL_ENTITY_BIGUPLUS,			// 0x2a04
	MANUAL_ENTITY_BIGSQCUP,			// 0x2a06
	MANUAL_ENTITY_IIIINT,			// 0x2a0c
	MANUAL_ENTITY_FPARTINT,			// 0x2a0d
	MANUAL_ENTITY_CIRFNINT,			// 0x2a10
	MANUAL_ENTITY_AWINT,			// 0x2a11
	MANUAL_ENTITY_RPPOLINT,			// 0x2a12
	MANUAL_ENTITY_SCPOLINT,			// 0x2a13
	MANUAL_ENTITY_NPOLINT,			// 0x2a14
	MANUAL_ENTITY_POINTINT,			// 0x2a15
	MANUAL_ENTITY_QUATINT,			// 0x2a16
	MANUAL_ENTITY_INTLARHK,			// 0x2a17
	MANUAL_ENTITY_PLUSCIR,			// 0x2a22
	MANUAL_ENTITY_PLUSACIR,			// 0x2a23
	MANUAL_ENTITY_SIMPLUS,			// 0x2a24
	MANUAL_ENTITY_PLUSDU,			// 0x2a25
	MANUAL_ENTITY_PLUSSIM,			// 0x2a26
	MANUAL_ENTITY_PLUSTWO,			// 0x2a27
	MANUAL_ENTITY_MCOMMA,			// 0x2a29
	MANUAL_ENTITY_MINUSDU,			// 0x2a2a
	MANUAL_ENTITY_LOPLUS,			// 0x2a2d
	MANUAL_ENTITY_ROPLUS,			// 0x2a2e
	MANUAL_ENTITY_VECTOR_PRODUCT,		// 0x2a2f
	MANUAL_ENTITY_TIMESD,			// 0x2a30
	MANUAL_ENTITY_TIMESBAR,			// 0x2a31
	MANUAL_ENTITY_SMASHP,			// 0x2a33
	MANUAL_ENTITY_LOTIMES,			// 0x2a34
	MANUAL_ENTITY_ROTIMES,			// 0x2a35
	MANUAL_ENTITY_OTIMESAS,			// 0x2a36
	MANUAL_ENTITY_CIRCLED_TIMES,		// 0x2a37
	MANUAL_ENTITY_ODIV,			// 0x2a38
	MANUAL_ENTITY_TRIPLUS,			// 0x2a39
	MANUAL_ENTITY_TRIMINUS,			// 0x2a3a
	MANUAL_ENTITY_TRITIME,			// 0x2a3b
	MANUAL_ENTITY_INTPROD,			// 0x2a3c
	MANUAL_ENTITY_AMALG,			// 0x2a3f
	MANUAL_ENTITY_CAPDOT,			// 0x2a40
	MANUAL_ENTITY_NCUP,			// 0x2a42
	MANUAL_ENTITY_NCAP,			// 0x2a43
	MANUAL_ENTITY_CAPAND,			// 0x2a44
	MANUAL_ENTITY_CUPOR,			// 0x2a45
	MANUAL_ENTITY_UNION_ABOVE_INTERSECT,	// 0x2a46
	MANUAL_ENTITY_CAPCUP,			// 0x2a47
	MANUAL_ENTITY_CUPBRCAP,			// 0x2a48
	MANUAL_ENTITY_CAPBRCUP,			// 0x2a49
	MANUAL_ENTITY_CUPCUP,			// 0x2a4a
	MANUAL_ENTITY_CAPCAP,			// 0x2a4b
	MANUAL_ENTITY_CCUPS,			// 0x2a4c
	MANUAL_ENTITY_CCAPS,			// 0x2a4d
	MANUAL_ENTITY_CCUPSSM,			// 0x2a50
	MANUAL_ENTITY_DOUBLE_LOGIC_AND,			// 0x2a53
	MANUAL_ENTITY_DOUBLE_LOGIC_OR,			// 0x2a54
	MANUAL_ENTITY_ANDAND,			// 0x2a55
	MANUAL_ENTITY_OROR,			// 0x2a56
	MANUAL_ENTITY_ORSLOPE,			// 0x2a57
	MANUAL_ENTITY_ANDSLOPE,			// 0x2a58
	MANUAL_ENTITY_ANDV,			// 0x2a5a
	MANUAL_ENTITY_ORV,			// 0x2a5b
	MANUAL_ENTITY_ANDD,			// 0x2a5c
	MANUAL_ENTITY_ORD,			// 0x2a5d
	MANUAL_ENTITY_WEDBAR,			// 0x2a5f
	MANUAL_ENTITY_SDOTE,			// 0x2a66
	MANUAL_ENTITY_SIMDOT,			// 0x2a6a
	MANUAL_ENTITY_CONGDOT,			// 0x2a6d
	MANUAL_ENTITY_EASTER,			// 0x2a6e
	MANUAL_ENTITY_APACIR,			// 0x2a6f
	MANUAL_ENTITY_APPROX_OR_EQUAL,		// 0x2a70
	MANUAL_ENTITY_EPLUS,			// 0x2a71
	MANUAL_ENTITY_PLUSE,			// 0x2a72
	MANUAL_ENTITY_ESIM,			// 0x2a73
	MANUAL_ENTITY_COLONE,			// 0x2a74
	MANUAL_ENTITY_EQUAL,			// 0x2a75
	MANUAL_ENTITY_DDOTSEQ,			// 0x2a77
	MANUAL_ENTITY_EQUIVDD,			// 0x2a78
	MANUAL_ENTITY_LTCIR,			// 0x2a79
	MANUAL_ENTITY_GTCIR,			// 0x2a7a
	MANUAL_ENTITY_LTQUEST,			// 0x2a7b
	MANUAL_ENTITY_GTQUEST,			// 0x2a7c
	MANUAL_ENTITY_LESSSLANTEQUAL,		// 0x2a7d
	MANUAL_ENTITY_GREATERSLANTEQUAL,	// 0x2a7e
	MANUAL_ENTITY_LESDOT,			// 0x2a7f
	MANUAL_ENTITY_GESDOT,			// 0x2a80
	MANUAL_ENTITY_LESDOTO,			// 0x2a81
	MANUAL_ENTITY_GESDOTO,			// 0x2a82
	MANUAL_ENTITY_LESDOTOR,			// 0x2a83
	MANUAL_ENTITY_GESDOTOL,			// 0x2a84
	MANUAL_ENTITY_LAP,			// 0x2a85
	MANUAL_ENTITY_GAP,			// 0x2a86
	MANUAL_ENTITY_L_SINGLE_LINE_NE,		// 0x2a87
	MANUAL_ENTITY_G_SINGLE_LINE_NE,		// 0x2a88
	MANUAL_ENTITY_LNAP,			// 0x2a89
	MANUAL_ENTITY_GNAP,			// 0x2a8a
	MANUAL_ENTITY_LEG,			// 0x2a8b
	MANUAL_ENTITY_GEL,			// 0x2a8c
	MANUAL_ENTITY_LSIME,			// 0x2a8d
	MANUAL_ENTITY_GSIME,			// 0x2a8e
	MANUAL_ENTITY_LSIMG,			// 0x2a8f
	MANUAL_ENTITY_GSIML,			// 0x2a90
	MANUAL_ENTITY_LGE,			// 0x2a91
	MANUAL_ENTITY_GLE,			// 0x2a92
	MANUAL_ENTITY_LESGES,			// 0x2a93
	MANUAL_ENTITY_GESLES,			// 0x2a94
	MANUAL_ENTITY_ELS,			// 0x2a95
	MANUAL_ENTITY_EGS,			// 0x2a96
	MANUAL_ENTITY_ELSDOT,			// 0x2a97
	MANUAL_ENTITY_EGSDOT,			// 0x2a98
	MANUAL_ENTITY_EL,			// 0x2a99
	MANUAL_ENTITY_EG,			// 0x2a9a
	MANUAL_ENTITY_SIML,			// 0x2a9d
	MANUAL_ENTITY_SIMG,			// 0x2a9e
	MANUAL_ENTITY_SIMLE,			// 0x2a9f
	MANUAL_ENTITY_SIMGE,			// 0x2aa0
	MANUAL_ENTITY_LESSLESS,			// 0x2aa1
	MANUAL_ENTITY_GREATERGREATER,		// 0x2aa2
	MANUAL_ENTITY_GLJ,			// 0x2aa4
	MANUAL_ENTITY_GLA,			// 0x2aa5
	MANUAL_ENTITY_LTCC,			// 0x2aa6
	MANUAL_ENTITY_GTCC,			// 0x2aa7
	MANUAL_ENTITY_LESCC,			// 0x2aa8
	MANUAL_ENTITY_GESCC,			// 0x2aa9
	MANUAL_ENTITY_SMT,			// 0x2aaa
	MANUAL_ENTITY_LAT,			// 0x2aab
	MANUAL_ENTITY_SMTE,			// 0x2aac
	MANUAL_ENTITY_LATE,			// 0x2aad
	MANUAL_ENTITY_BUMPE,			// 0x2aae
	MANUAL_ENTITY_PRECEDESEQUAL,		// 0x2aaf
	MANUAL_ENTITY_SUCCEEDSEQUAL,		// 0x2ab0
	MANUAL_ENTITY_PRE,			// 0x2ab3
	MANUAL_ENTITY_SCE,			// 0x2ab4
	MANUAL_ENTITY_PRECNEQQ,			// 0x2ab5
	MANUAL_ENTITY_SCNE,			// 0x2ab6
	MANUAL_ENTITY_PRAP,			// 0x2ab7
	MANUAL_ENTITY_SCAP,			// 0x2ab8
	MANUAL_ENTITY_PRECNAPPROX,		// 0x2ab9
	MANUAL_ENTITY_SCNAP,			// 0x2aba
	MANUAL_ENTITY_PR,			// 0x2abb
	MANUAL_ENTITY_SC,			// 0x2abc
	MANUAL_ENTITY_SUBDOT,			// 0x2abd
	MANUAL_ENTITY_SUPDOT,			// 0x2abe
	MANUAL_ENTITY_SUBPLUS,			// 0x2abf
	MANUAL_ENTITY_SUPPLUS,			// 0x2ac0
	MANUAL_ENTITY_SUBMULT,			// 0x2ac1
	MANUAL_ENTITY_SUPMULT,			// 0x2ac2
	MANUAL_ENTITY_SUBEDOT,			// 0x2ac3
	MANUAL_ENTITY_SUPEDOT,			// 0x2ac4
	MANUAL_ENTITY_SUBSET_ABOVE_EQ,		// 0x2ac5
	MANUAL_ENTITY_SUPERSET_ABOVE_EQ,	// 0x2ac6
	MANUAL_ENTITY_SUBSIM,			// 0x2ac7
	MANUAL_ENTITY_SUPSIM,			// 0x2ac8
	MANUAL_ENTITY_SUBSET_ABOVE_NE,		// 0x2acb
	MANUAL_ENTITY_SUPERSET_ABOVE_NE,	// 0x2acc
	MANUAL_ENTITY_CSUB,			// 0x2acf
	MANUAL_ENTITY_CSUP,			// 0x2ad0
	MANUAL_ENTITY_CSUBE,			// 0x2ad1
	MANUAL_ENTITY_CSUPE,			// 0x2ad2
	MANUAL_ENTITY_SUBSUP,			// 0x2ad3
	MANUAL_ENTITY_SUPSUB,			// 0x2ad4
	MANUAL_ENTITY_SUBSUB,			// 0x2ad5
	MANUAL_ENTITY_SUPSUP,			// 0x2ad6
	MANUAL_ENTITY_SUPHSUB,			// 0x2ad7
	MANUAL_ENTITY_SUPDSUB,			// 0x2ad8
	MANUAL_ENTITY_FORKV,			// 0x2ad9
	MANUAL_ENTITY_TOPFORK,			// 0x2ada
	MANUAL_ENTITY_MLCP,			// 0x2adb
	MANUAL_ENTITY_DASHV,			// 0x2ae4
	MANUAL_ENTITY_VDASHL,			// 0x2ae6
	MANUAL_ENTITY_BARV,			// 0x2ae7
	MANUAL_ENTITY_SHORT_UPTACK_UBAR,	// 0x2ae8
	MANUAL_ENTITY_VBARV,			// 0x2ae9
	MANUAL_ENTITY_DOUBLE_UPTACK,		// 0x2aeb
	MANUAL_ENTITY_DOUBLE_NOT,		// 0x2aec
	MANUAL_ENTITY_DOUBLE_REVERSED_NOT,	// 0x2aed
	MANUAL_ENTITY_RNMID,			// 0x2aee
	MANUAL_ENTITY_CIRMID,			// 0x2aef
	MANUAL_ENTITY_MIDCIR,			// 0x2af0
	MANUAL_ENTITY_TOPCIR,			// 0x2af1
	MANUAL_ENTITY_NHPAR,			// 0x2af2
	MANUAL_ENTITY_PARSIM,			// 0x2af3
	MANUAL_ENTITY_PARSL,			// 0x2afd

	/* Alphabetic Presentation Forms */

	MANUAL_ENTITY_FFLIG_L,			// 0xfb00
	MANUAL_ENTITY_FILIG_L,			// 0xfb01
	MANUAL_ENTITY_FLLIG_L,			// 0xfb02
	MANUAL_ENTITY_FFILIG_L,			// 0xfb03
	MANUAL_ENTITY_FFLLIG_L,			// 0xfb04

	/* Mathematical Alphanumeric Symbols */

	MANUAL_ENTITY_ASCR_U,			// 0x1d49c
	MANUAL_ENTITY_CSCR_U,			// 0x1d49e
	MANUAL_ENTITY_DSCR_U,			// 0x1d49f
	MANUAL_ENTITY_GSCR_U,			// 0x1d4a2
	MANUAL_ENTITY_JSCR_U,			// 0x1d4a5
	MANUAL_ENTITY_KSCR_U,			// 0x1d4a6
	MANUAL_ENTITY_NSCR_U,			// 0x1d4a9
	MANUAL_ENTITY_OSCR_U,			// 0x1d4aa
	MANUAL_ENTITY_PSCR_U,			// 0x1d4ab
	MANUAL_ENTITY_QSCR_U,			// 0x1d4ac
	MANUAL_ENTITY_SSCR_U,			// 0x1d4ae
	MANUAL_ENTITY_TSCR_U,			// 0x1d4af
	MANUAL_ENTITY_USCR_U,			// 0x1d4b0
	MANUAL_ENTITY_VSCR_U,			// 0x1d4b1
	MANUAL_ENTITY_WSCR_U,			// 0x1d4b2
	MANUAL_ENTITY_XSCR_U,			// 0x1d4b3
	MANUAL_ENTITY_YSCR_U,			// 0x1d4b4
	MANUAL_ENTITY_ZSCR_U,			// 0x1d4b5
	MANUAL_ENTITY_ASCR_L,			// 0x1d4b6
	MANUAL_ENTITY_BSCR_L,			// 0x1d4b7
	MANUAL_ENTITY_CSCR_L,			// 0x1d4b8
	MANUAL_ENTITY_DSCR_L,			// 0x1d4b9
	MANUAL_ENTITY_FSCR_L,			// 0x1d4bb
	MANUAL_ENTITY_HSCR_L,			// 0x1d4bd
	MANUAL_ENTITY_ISCR_L,			// 0x1d4be
	MANUAL_ENTITY_JSCR_L,			// 0x1d4bf
	MANUAL_ENTITY_KSCR_L,			// 0x1d4c0
	MANUAL_ENTITY_LSCR_L,			// 0x1d4c1
	MANUAL_ENTITY_MSCR_L,			// 0x1d4c2
	MANUAL_ENTITY_NSCR_L,			// 0x1d4c3
	MANUAL_ENTITY_PSCR_L,			// 0x1d4c5
	MANUAL_ENTITY_QSCR_L,			// 0x1d4c6
	MANUAL_ENTITY_RSCR_L,			// 0x1d4c7
	MANUAL_ENTITY_SSCR_L,			// 0x1d4c8
	MANUAL_ENTITY_TSCR_L,			// 0x1d4c9
	MANUAL_ENTITY_USCR_L,			// 0x1d4ca
	MANUAL_ENTITY_VSCR_L,			// 0x1d4cb
	MANUAL_ENTITY_WSCR_L,			// 0x1d4cc
	MANUAL_ENTITY_XSCR_L,			// 0x1d4cd
	MANUAL_ENTITY_YSCR_L,			// 0x1d4ce
	MANUAL_ENTITY_ZSCR_L,			// 0x1d4cf
	MANUAL_ENTITY_AFR_U,			// 0x1d504
	MANUAL_ENTITY_BFR_U,			// 0x1d505
	MANUAL_ENTITY_DFR_U,			// 0x1d507
	MANUAL_ENTITY_EFR_U,			// 0x1d508
	MANUAL_ENTITY_FFR_U,			// 0x1d509
	MANUAL_ENTITY_GFR_U,			// 0x1d50a
	MANUAL_ENTITY_JFR_U,			// 0x1d50d
	MANUAL_ENTITY_KFR_U,			// 0x1d50e
	MANUAL_ENTITY_LFR_U,			// 0x1d50f
	MANUAL_ENTITY_MFR_U,			// 0x1d510
	MANUAL_ENTITY_NFR_U,			// 0x1d511
	MANUAL_ENTITY_OFR_U,			// 0x1d512
	MANUAL_ENTITY_PFR_U,			// 0x1d513
	MANUAL_ENTITY_QFR_U,			// 0x1d514
	MANUAL_ENTITY_SFR_U,			// 0x1d516
	MANUAL_ENTITY_TFR_U,			// 0x1d517
	MANUAL_ENTITY_UFR_U,			// 0x1d518
	MANUAL_ENTITY_VFR_U,			// 0x1d519
	MANUAL_ENTITY_WFR_U,			// 0x1d51a
	MANUAL_ENTITY_XFR_U,			// 0x1d51b
	MANUAL_ENTITY_YFR_U,			// 0x1d51c
	MANUAL_ENTITY_AFR_L,			// 0x1d51e
	MANUAL_ENTITY_BFR_L,			// 0x1d51f
	MANUAL_ENTITY_CFR_L,			// 0x1d520
	MANUAL_ENTITY_DFR_L,			// 0x1d521
	MANUAL_ENTITY_EFR_L,			// 0x1d522
	MANUAL_ENTITY_FFR_L,			// 0x1d523
	MANUAL_ENTITY_GFR_L,			// 0x1d524
	MANUAL_ENTITY_HFR_L,			// 0x1d525
	MANUAL_ENTITY_IFR_L,			// 0x1d526
	MANUAL_ENTITY_JFR_L,			// 0x1d527
	MANUAL_ENTITY_KFR_L,			// 0x1d528
	MANUAL_ENTITY_LFR_L,			// 0x1d529
	MANUAL_ENTITY_MFR_L,			// 0x1d52a
	MANUAL_ENTITY_NFR_L,			// 0x1d52b
	MANUAL_ENTITY_OFR_L,			// 0x1d52c
	MANUAL_ENTITY_PFR_L,			// 0x1d52d
	MANUAL_ENTITY_QFR_L,			// 0x1d52e
	MANUAL_ENTITY_RFR_L,			// 0x1d52f
	MANUAL_ENTITY_SFR_L,			// 0x1d530
	MANUAL_ENTITY_TFR_L,			// 0x1d531
	MANUAL_ENTITY_UFR_L,			// 0x1d532
	MANUAL_ENTITY_VFR_L,			// 0x1d533
	MANUAL_ENTITY_WFR_L,			// 0x1d534
	MANUAL_ENTITY_XFR_L,			// 0x1d535
	MANUAL_ENTITY_YFR_L,			// 0x1d536
	MANUAL_ENTITY_ZFR_L,			// 0x1d537
	MANUAL_ENTITY_AOPF_U,			// 0x1d538
	MANUAL_ENTITY_BOPF_U,			// 0x1d539
	MANUAL_ENTITY_DOPF_U,			// 0x1d53b
	MANUAL_ENTITY_EOPF_U,			// 0x1d53c
	MANUAL_ENTITY_FOPF_U,			// 0x1d53d
	MANUAL_ENTITY_GOPF_U,			// 0x1d53e
	MANUAL_ENTITY_IOPF_U,			// 0x1d540
	MANUAL_ENTITY_JOPF_U,			// 0x1d541
	MANUAL_ENTITY_KOPF_U,			// 0x1d542
	MANUAL_ENTITY_LOPF_U,			// 0x1d543
	MANUAL_ENTITY_MOPF_U,			// 0x1d544
	MANUAL_ENTITY_OOPF_U,			// 0x1d546
	MANUAL_ENTITY_SOPF_U,			// 0x1d54a
	MANUAL_ENTITY_TOPF_U,			// 0x1d54b
	MANUAL_ENTITY_UOPF_U,			// 0x1d54c
	MANUAL_ENTITY_VOPF_U,			// 0x1d54d
	MANUAL_ENTITY_WOPF_U,			// 0x1d54e
	MANUAL_ENTITY_XOPF_U,			// 0x1d54f
	MANUAL_ENTITY_YOPF_U,			// 0x1d550
	MANUAL_ENTITY_AOPF_L,			// 0x1d552
	MANUAL_ENTITY_BOPF_L,			// 0x1d553
	MANUAL_ENTITY_COPF_L,			// 0x1d554
	MANUAL_ENTITY_DOPF_L,			// 0x1d555
	MANUAL_ENTITY_EOPF_L,			// 0x1d556
	MANUAL_ENTITY_FOPF_L,			// 0x1d557
	MANUAL_ENTITY_GOPF_L,			// 0x1d558
	MANUAL_ENTITY_HOPF_L,			// 0x1d559
	MANUAL_ENTITY_IOPF_L,			// 0x1d55a
	MANUAL_ENTITY_JOPF_L,			// 0x1d55b
	MANUAL_ENTITY_KOPF_L,			// 0x1d55c
	MANUAL_ENTITY_LOPF_L,			// 0x1d55d
	MANUAL_ENTITY_MOPF_L,			// 0x1d55e
	MANUAL_ENTITY_NOPF_L,			// 0x1d55f
	MANUAL_ENTITY_OOPF_L,			// 0x1d560
	MANUAL_ENTITY_POPF_L,			// 0x1d561
	MANUAL_ENTITY_QOPF_L,			// 0x1d562
	MANUAL_ENTITY_ROPF_L,			// 0x1d563
	MANUAL_ENTITY_SOPF_L,			// 0x1d564
	MANUAL_ENTITY_TOPF_L,			// 0x1d565
	MANUAL_ENTITY_UOPF_L,			// 0x1d566
	MANUAL_ENTITY_VOPF_L,			// 0x1d567
	MANUAL_ENTITY_WOPF_L,			// 0x1d568
	MANUAL_ENTITY_XOPF_L,			// 0x1d569
	MANUAL_ENTITY_YOPF_L,			// 0x1d56a
	MANUAL_ENTITY_ZOPF_L,			// 0x1d56b

	/* End of List */

	MANUAL_ENTITY_NONE
};

/**
 * Given a node containing an entity, return the entity type.
 *
 * \param *name		Pointer to the textual entity name.
 * \return		The entity type, or MANUAL_ENTITY_NONE if unknown.
 */

enum manual_entity_type manual_entity_find_type(char *name);

/**
 * Given an entity type, return the textual entity name.
 *
 * \param type		The entity type to look up.
 * \return		Pointer to the entity's textual name, or to "" if
 *			the type was not recognised.
 */

const char *manual_entity_find_name(enum manual_entity_type type);

/**
 * Given an entity type, return the Unicode codepoint.
 *
 * \param type		The entity type to look up.
 * \return		The Unicode codepoint, or -1 if not recognised.
 */

int manual_entity_find_codepoint(enum manual_entity_type type);

/**
 * Given a unicode code point, return an appropriate entity name
 * if one exists.
 *
 * \param type		The entity type to look up.
 * \return		Pointer to the entity's textual name, or to "" if
 *			the type was not recognised.
 */

const char *manual_entity_find_name_from_codepoint(int codepoint);

#endif
